-- This file is generated by scripts/generate_changelog_lua.py. Do not edit manually.
local _, addon = ...

addon.GeneratedChangelog = {
	sourceTag = "12.5.0",
	releases = {
		{
			tag = "12.5.0",
			date = "2026-08-17",
			sections = {
				{
					title = "Added",
					items = {
						"Cooldown Panels: Added an optional automatic color for tracked aura bars at maximum stacks.",
						"Cooldown Panels: Added a per-entry option to track one talent from a choice node separately.",
						"Unit Frames: Healer Buff Placement rules can now target Party, Raid, friendly Target, Focus, and Boss frames independently.",
					},
				},
				{
					title = "Changed",
					items = {
						"Cooldown Panels: New panels now use Center as their default Growth Point.",
					},
				},
				{
					title = "Fixed",
					items = {
						"Cooldown Panels: Centered vertically growing tracked-aura grids around their configured anchor.",
						"Cooldown Panels: Made Growth Point available for non-radial layouts without requiring wrapping.",
					},
				},
			},
		},
	},
}
