-- This file is generated by scripts/generate_changelog_lua.py. Do not edit manually.
local _, addon = ...

addon.GeneratedChangelog = {
	sourceTag = "11.9.1",
	releases = {
		{
			tag = "11.9.1",
			date = "2026-07-24",
			sections = {
				{
					title = "Fixed",
					items = {
						"Bags: Kept looted items and item cooldowns updating immediately during combat.",
						"Cooldown Panels: Kept panel, icon, and border edges evenly pixel-aligned across UI scales, frame positions, and reloads.",
					},
				},
			},
		},
		{
			tag = "11.9.0",
			date = "2026-07-24",
			sections = {
				{
					title = "Added",
					items = {
						"Damage Meter: Added compact K/M/B numbers, a pause keybind, persistent manual visibility, and Data Broker quick controls for all windows.",
						"Damage Meter: Added optional moving and resizing outside Edit Mode, with mouseover and lock controls in the Behavior settings and window menu.",
						"Unit Frames: Added optional customizable main resource colors to the central Settings UI.",
					},
				},
				{
					title = "Changed",
					items = {
						"Cooldown Panels: Reordered per-entry ready-glow controls to make overrides easier to configure.",
						"Damage Meter: Added the global update interval to Edit Mode and expanded its supported range down to 0.01 seconds.",
						"Unit Frames: Class-colored player names are now used for the target-of-target name, rare classification text no longer adds a gap after the level, and the legacy status-row height no longer extends the clickable frame area.",
					},
				},
				{
					title = "PTR 12.1 Only",
					items = {
						"Unit Frames, Group Frames, and Default Aura Frames: Updated native AuraContainer handling, including managed aura groups, friendly debuff filters, dispel overlays, vertical layouts, restricted-unit handling, combat-safe creation, and click-to-cancel support.",
						"Cooldown Panels and Bloodlust Tracker: Updated native aura progress, glows, cooldown swipes, sounds, and restricted-value handling; Cooldown Panels now support separate sounds for initial application, gained applications, and removal.",
						"Group Tools: Updated Healer Mana event handling for restricted role values.",
						"Resource Bars: Added native application-count progress for stack-based aura resources.",
					},
				},
				{
					title = "Fixed",
					items = {
						"Class Buff Reminder: Kept shaped glows correct when the reminder first appears after login or reload.",
						"Cooldown Panels: Kept synced Cooldown Manager entries stable when proc effects temporarily replace their spells.",
						"Group Frames: Stopped disabled and unused secure group headers from consuming CPU while idle.",
						"Minimap: Kept the loot and active specialization Quick Switch popup within the screen boundaries.",
						"Resource Bars: Kept borders and segments evenly pixel-aligned across UI scales and odd or even bar sizes.",
						"Teleport Compendium: Ensured equippable teleport rings and trinkets use their intended equipment slot.",
						"Unit Frames: Kept one-pixel borders even and gap-free across UI scales and odd or even frame sizes.",
						"Unit Frames: Preserved existing profile layouts when a newly mapped character logs in after another Unit Frames profile was active.",
					},
				},
			},
		},
	},
}
