local addonName, addon = ...

addon.variables.NewVersionTableEQOL = {
	-- 12.9.0
	ClassBuffReminderExpirationWarningMythicDungeon = true,
	ClassBuffReminderExpirationWarningRaid = true,
	ClassBuffReminderPetHealthInfernalBeneficiaryOnly = true,
	ClassBuffReminderPetHealthReminder = true,
	ClassBuffReminderPetHealthThreshold = true,
	autoChooseGossipManualOnly = true,
	KeystonePartyFrame = true,
	partyKeystoneDungeonIndicatorEnabled = true,
	partyKeystoneFrameAnchor = true,
	partyKeystoneFrameAutoWidth = true,
	partyKeystoneFrameBackgroundColor = true,
	partyKeystoneFrameBorderColor = true,
	partyKeystoneFrameBorderEnabled = true,
	partyKeystoneFrameBorderSize = true,
	partyKeystoneFrameBorderStyle = true,
	partyKeystoneFrameFont = true,
	partyKeystoneFrameFontStyle = true,
	partyKeystoneFrameHeight = true,
	partyKeystoneFrameIconSize = true,
	partyKeystoneFrameLevelColor = true,
	partyKeystoneFrameLevelFontSize = true,
	partyKeystoneFrameLocationColor = true,
	partyKeystoneFrameLocationFontSize = true,
	partyKeystoneFrameNameColor = true,
	partyKeystoneFrameNameFontSize = true,
	partyKeystoneFrameOffsetX = true,
	partyKeystoneFrameOffsetY = true,
	partyKeystoneFrameShowIcon = true,
	partyKeystoneFrameShowRealm = true,
	partyKeystoneFrameUseClassColor = true,
	partyKeystoneFrameWidth = true,

	-- 12.8.0
	nameplateCastTextSize = true,
	chatBubblesDisableInInstances = true,
	ufBossRangeFade = true,
}
