-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('deDE') -- luacheck: ignore
L["Artwork opacity"] = "Artwork-Deckkraft"
L["Artwork style"] = "Artwork-Stil"
L["Button scale"] = "Schaltflächenmaßstab"
L["Hide cooldown text"] = "Abklingtext ausblenden"
L["Only show for quests in current zone"] = "Nur Quests in der aktuellen Zone anzeigen"
L["Only show for tracked quests"] = "Nur verfolgte Quests anzeigen"
L["Tracking distance"] = "Verfolgungsreichweite"

