-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('esMX') -- luacheck: ignore
L["Artwork opacity"] = "Opacidad del arte"
L["Artwork style"] = "Estilo del arte"
L["Button scale"] = "Escala del botón"
L["Hide cooldown text"] = "Ocultar texto de tiempo de reutilización"
L["Only show for quests in current zone"] = "Mostrar solo para misiones en la zona actual"
L["Only show for tracked quests"] = "Mostrar solo para misiones rastreadas"
L["Tracking distance"] = "Distancia de seguimiento"

