-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('frFR') -- luacheck: ignore
L["Artwork opacity"] = "Opacité de l'œuvre"
L["Artwork style"] = "Style de l'œuvre"
L["Button scale"] = "Échelle du bouton"
L["Hide cooldown text"] = "Masquer le texte de temps de recharge"
L["Only show for quests in current zone"] = "Afficher uniquement pour les quêtes dans la zone actuelle"
L["Only show for tracked quests"] = "Afficher uniquement pour les quêtes suivies"
L["Tracking distance"] = "Distance de suivi"

