-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('itIT') -- luacheck: ignore
L["Artwork opacity"] = "Opacità dell'opera d'arte"
L["Artwork style"] = "Stile dell'opera d'arte"
L["Button scale"] = "Scala del pulsante"
L["Hide cooldown text"] = "Nascondi il testo del tempo di recupero"
L["Only show for quests in current zone"] = "Mostra solo per le missioni nella zona corrente"
L["Only show for tracked quests"] = "Mostra solo per le missioni seguite"
L["Tracking distance"] = "Distanza di tracciamento"

