-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('koKR') -- luacheck: ignore
L["Artwork opacity"] = "아트워크 불투명도"
L["Artwork style"] = "아트워크 스타일"
L["Button scale"] = "버튼 크기 배율"
L["Hide cooldown text"] = "재사용 대기시간 텍스트 숨기기"
L["Only show for quests in current zone"] = "현재 지역의 퀘스트만 표시"
L["Only show for tracked quests"] = "추적 중인 퀘스트만 표시"
L["Tracking distance"] = "추적 거리"

