-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('ruRU') -- luacheck: ignore
L["Artwork opacity"] = "Непрозрачность изображения"
L["Artwork style"] = "Стиль изображения"
L["Button scale"] = "Масштаб кнопки"
L["Hide cooldown text"] = "Скрыть текст перезарядки"
L["Only show for quests in current zone"] = "Показывать только для заданий в текущей зоне"
L["Only show for tracked quests"] = "Показывать только для отслеживаемых заданий"
L["Tracking distance"] = "Расстояние отслеживания"

