-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('zhCN') -- luacheck: ignore
L["Artwork opacity"] = "艺术品不透明度"
L["Artwork style"] = "艺术品风格"
L["Button scale"] = "按钮缩放"
L["Hide cooldown text"] = "隐藏冷却文本"
L["Only show for quests in current zone"] = "仅在当前区域显示任务"
L["Only show for tracked quests"] = "仅显示已追踪任务"
L["Tracking distance"] = "追踪距离"

