-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('zhTW') -- luacheck: ignore
L["Artwork opacity"] = "藝術品不透明度"
L["Artwork style"] = "藝術品風格"
L["Button scale"] = "按鈕縮放"
L["Hide cooldown text"] = "隱藏冷卻時間文字"
L["Only show for quests in current zone"] = "僅對當前區域的任務顯示"
L["Only show for tracked quests"] = "僅顯示已追蹤任務"
L["Tracking distance"] = "追蹤距離"

