-- This file is generated by scripts/update_tooltip_realm_info.py.
-- Source data is generated from Blizzard's World of Warcraft Game Data API.
-- Generated at: 2026-05-16T06:28:43Z
-- Source: Blizzard World of Warcraft Game Data API (EU, US, KR, TW)

local parentAddonName = "EnhanceQoL"
local addonName, addon = ...

if _G[parentAddonName] then
	addon = _G[parentAddonName]
else
	error(parentAddonName .. " is not loaded")
end

addon.Tooltip = addon.Tooltip or {}
addon.Tooltip.variables = addon.Tooltip.variables or {}

local realmInfo = addon.Tooltip.variables.realmInfo or {}
addon.Tooltip.variables.realmInfo = realmInfo

realmInfo.generatedAt = "2026-05-16T06:28:43Z"
realmInfo.source = "Blizzard World of Warcraft Game Data API (EU, US, KR, TW)"

local timezone2utc = {
	AEST = 10,
	BRT = -3,
	CET = 1,
	CNST = 8,
	CST = -6,
	EST = -5,
	KST = 9,
	MST = -7,
	PST = -8,
}

local rawRealmData = {
	[1] = "Lightbringer,PvE,enUS,US,America/Los_Angeles,lightbringer,retail,",
	[2] = "Cenarius,PvE,enUS,US,America/Los_Angeles,cenarius,retail,",
	[3] = "Uther,PvE,enUS,US,America/Chicago,uther,retail,",
	[4] = "Kilrogg,PvE,enUS,US,America/Los_Angeles,kilrogg,retail,",
	[5] = "Proudmoore,PvE,enUS,US,America/Los_Angeles,proudmoore,retail,",
	[6] = "Hyjal,PvE,enUS,US,America/Los_Angeles,hyjal,retail,",
	[7] = "Frostwolf,PvE,enUS,US,America/New_York,frostwolf,retail,",
	[8] = "Ner'zhul,PvE,enUS,US,America/Los_Angeles,nerzhul,retail,",
	[9] = "Kil'jaeden,PvE,enUS,US,America/Los_Angeles,kiljaeden,retail,",
	[10] = "Blackrock,PvE,enUS,US,America/Denver,blackrock,retail,",
	[11] = "Tichondrius,PvE,enUS,US,America/Los_Angeles,tichondrius,retail,",
	[12] = "Silver Hand,RP,enUS,US,America/Los_Angeles,silver-hand,retail,",
	[13] = "Doomhammer,PvE,enUS,US,America/Los_Angeles,doomhammer,retail,",
	[14] = "Icecrown,PvE,enUS,US,America/Chicago,icecrown,retail,",
	[15] = "Deathwing,PvE,enUS,US,America/Los_Angeles,deathwing,retail,",
	[16] = "Kel'Thuzad,PvE,enUS,US,America/Denver,kelthuzad,retail,",
	[47] = "Eitrigg,PvE,enUS,US,America/Chicago,eitrigg,retail,",
	[51] = "Garona,PvE,enUS,US,America/Chicago,garona,retail,",
	[52] = "Alleria,PvE,enUS,US,America/Chicago,alleria,retail,",
	[53] = "Hellscream,PvE,enUS,US,America/Chicago,hellscream,retail,",
	[54] = "Blackhand,PvE,enUS,US,America/Chicago,blackhand,retail,",
	[55] = "Whisperwind,PvE,enUS,US,America/Chicago,whisperwind,retail,",
	[56] = "Archimonde,PvE,enUS,US,America/Chicago,archimonde,retail,",
	[57] = "Illidan,PvE,enUS,US,America/Chicago,illidan,retail,",
	[58] = "Stormreaver,PvE,enUS,US,America/Chicago,stormreaver,retail,",
	[59] = "Mal'Ganis,PvE,enUS,US,America/Chicago,malganis,retail,",
	[60] = "Stormrage,PvE,enUS,US,America/New_York,stormrage,retail,",
	[61] = "Zul'jin,PvE,enUS,US,America/New_York,zuljin,retail,",
	[62] = "Medivh,PvE,enUS,US,America/Chicago,medivh,retail,",
	[63] = "Durotan,PvE,enUS,US,America/New_York,durotan,retail,",
	[64] = "Bloodhoof,PvE,enUS,US,America/New_York,bloodhoof,retail,",
	[65] = "Khadgar,PvE,enUS,US,America/Chicago,khadgar,retail,",
	[66] = "Dalaran,PvE,enUS,US,America/New_York,dalaran,retail,",
	[67] = "Elune,PvE,enUS,US,America/New_York,elune,retail,",
	[68] = "Lothar,PvE,enUS,US,America/New_York,lothar,retail,",
	[69] = "Arthas,PvE,enUS,US,America/New_York,arthas,retail,",
	[70] = "Mannoroth,PvE,enUS,US,America/Chicago,mannoroth,retail,",
	[71] = "Warsong,PvE,enUS,US,America/New_York,warsong,retail,",
	[72] = "Shattered Hand,PvE,enUS,US,America/Los_Angeles,shattered-hand,retail,",
	[73] = "Bleeding Hollow,PvE,enUS,US,America/New_York,bleeding-hollow,retail,",
	[74] = "Skullcrusher,PvE,enUS,US,America/New_York,skullcrusher,retail,",
	[75] = "Argent Dawn,RP,enUS,US,America/New_York,argent-dawn,retail,",
	[76] = "Sargeras,PvE,enUS,US,America/Chicago,sargeras,retail,",
	[77] = "Azgalor,PvE,enUS,US,America/Chicago,azgalor,retail,",
	[78] = "Magtheridon,PvE,enUS,US,America/New_York,magtheridon,retail,",
	[79] = "Destromath,PvE,enUS,US,America/Chicago,destromath,retail,",
	[80] = "Gorgonnash,PvE,enUS,US,America/New_York,gorgonnash,retail,",
	[81] = "Dethecus,PvE,enUS,US,America/Chicago,dethecus,retail,",
	[82] = "Spinebreaker,PvE,enUS,US,America/Chicago,spinebreaker,retail,",
	[83] = "Bonechewer,PvE,enUS,US,America/Chicago,bonechewer,retail,",
	[84] = "Dragonmaw,PvE,enUS,US,America/Los_Angeles,dragonmaw,retail,",
	[85] = "Shadowsong,PvE,enUS,US,America/Los_Angeles,shadowsong,retail,",
	[86] = "Silvermoon,PvE,enUS,US,America/Los_Angeles,silvermoon,retail,",
	[87] = "Windrunner,PvE,enUS,US,America/Los_Angeles,windrunner,retail,",
	[88] = "Cenarion Circle,RP,enUS,US,America/Denver,cenarion-circle,retail,",
	[89] = "Nathrezim,PvE,enUS,US,America/Chicago,nathrezim,retail,",
	[90] = "Terenas,PvE,enUS,US,America/Los_Angeles,terenas,retail,",
	[91] = "Burning Blade,PvE,enUS,US,America/Chicago,burning-blade,retail,",
	[92] = "Gorefiend,PvE,enUS,US,America/Chicago,gorefiend,retail,",
	[93] = "Eredar,PvE,enUS,US,America/Chicago,eredar,retail,",
	[94] = "Shadowmoon,PvE,enUS,US,America/Chicago,shadowmoon,retail,",
	[95] = "Lightning's Blade,PvE,enUS,US,America/Chicago,lightnings-blade,retail,",
	[96] = "Eonar,PvE,enUS,US,America/New_York,eonar,retail,",
	[97] = "Gilneas,PvE,enUS,US,America/New_York,gilneas,retail,",
	[98] = "Kargath,PvE,enUS,US,America/Chicago,kargath,retail,",
	[99] = "Llane,PvE,enUS,US,America/New_York,llane,retail,",
	[100] = "Earthen Ring,RP,enUS,US,America/New_York,earthen-ring,retail,",
	[101] = "Laughing Skull,PvE,enUS,US,America/New_York,laughing-skull,retail,",
	[102] = "Burning Legion,PvE,enUS,US,America/Chicago,burning-legion,retail,",
	[103] = "Thunderlord,PvE,enUS,US,America/Chicago,thunderlord,retail,",
	[104] = "Malygos,PvE,enUS,US,America/Chicago,malygos,retail,",
	[105] = "Thunderhorn,PvE,enUS,US,America/Chicago,thunderhorn,retail,",
	[106] = "Aggramar,PvE,enUS,US,America/Chicago,aggramar,retail,",
	[107] = "Crushridge,PvE,enUS,US,America/Chicago,crushridge,retail,",
	[108] = "Stonemaul,PvE,enUS,US,America/Chicago,stonemaul,retail,",
	[109] = "Daggerspine,PvE,enUS,US,America/Chicago,daggerspine,retail,",
	[110] = "Stormscale,PvE,enUS,US,America/New_York,stormscale,retail,",
	[111] = "Dunemaul,PvE,enUS,US,America/Chicago,dunemaul,retail,",
	[112] = "Boulderfist,PvE,enUS,US,America/Chicago,boulderfist,retail,",
	[113] = "Suramar,PvE,enUS,US,America/Los_Angeles,suramar,retail,",
	[114] = "Dragonblight,PvE,enUS,US,America/Los_Angeles,dragonblight,retail,",
	[115] = "Draenor,PvE,enUS,US,America/Los_Angeles,draenor,retail,",
	[116] = "Uldum,PvE,enUS,US,America/Los_Angeles,uldum,retail,",
	[117] = "Bronzebeard,PvE,enUS,US,America/Los_Angeles,bronzebeard,retail,",
	[118] = "Feathermoon,RP,enUS,US,America/Los_Angeles,feathermoon,retail,",
	[119] = "Bloodscalp,PvE,enUS,US,America/Chicago,bloodscalp,retail,",
	[120] = "Darkspear,PvE,enUS,US,America/Denver,darkspear,retail,",
	[121] = "Azjol-Nerub,PvE,enUS,US,America/Denver,azjolnerub,retail,",
	[122] = "Perenolde,PvE,enUS,US,America/Los_Angeles,perenolde,retail,",
	[123] = "Eldre'Thalas,PvE,enUS,US,America/Los_Angeles,eldrethalas,retail,",
	[124] = "Spirestone,PvE,enUS,US,America/New_York,spirestone,retail,",
	[125] = "Shadow Council,RP,enUS,US,America/Denver,shadow-council,retail,",
	[126] = "Scarlet Crusade,RP,enUS,US,America/Los_Angeles,scarlet-crusade,retail,",
	[127] = "Firetree,PvE,enUS,US,America/New_York,firetree,retail,",
	[128] = "Frostmane,PvE,enUS,US,America/Los_Angeles,frostmane,retail,",
	[129] = "Gurubashi,PvE,enUS,US,America/Chicago,gurubashi,retail,",
	[130] = "Smolderthorn,PvE,enUS,US,America/Chicago,smolderthorn,retail,",
	[131] = "Skywall,PvE,enUS,US,America/Los_Angeles,skywall,retail,",
	[151] = "Runetotem,PvE,enUS,US,America/Chicago,runetotem,retail,",
	[153] = "Moonrunner,PvE,enUS,US,America/New_York,moonrunner,retail,",
	[154] = "Detheroc,PvE,enUS,US,America/Chicago,detheroc,retail,",
	[155] = "Kalecgos,PvE,enUS,US,America/Los_Angeles,kalecgos,retail,",
	[156] = "Ursin,PvE,enUS,US,America/New_York,ursin,retail,",
	[157] = "Dark Iron,PvE,enUS,US,America/Los_Angeles,dark-iron,retail,",
	[158] = "Greymane,PvE,enUS,US,America/Chicago,greymane,retail,",
	[159] = "Wildhammer,PvE,enUS,US,America/Chicago,wildhammer,retail,",
	[160] = "Staghelm,PvE,enUS,US,America/Chicago,staghelm,retail,",
	[162] = "Emerald Dream,RP,enUS,US,America/Chicago,emerald-dream,retail,",
	[163] = "Maelstrom,RP,enUS,US,America/Chicago,maelstrom,retail,",
	[164] = "Twisting Nether,RP,enUS,US,America/Chicago,twisting-nether,retail,",
	[201] = "불타는 군단,PvE,koKR,KR,Asia/Seoul,burning-legion,retail,",
	[205] = "아즈샤라,PvE,koKR,KR,Asia/Seoul,azshara,retail,",
	[207] = "달라란,PvE,koKR,KR,Asia/Seoul,dalaran,retail,",
	[210] = "듀로탄,PvE,koKR,KR,Asia/Seoul,durotan,retail,",
	[211] = "노르간논,PvE,koKR,KR,Asia/Seoul,norgannon,retail,",
	[212] = "가로나,PvE,koKR,KR,Asia/Seoul,garona,retail,",
	[214] = "윈드러너,PvE,koKR,KR,Asia/Seoul,windrunner,retail,",
	[215] = "굴단,PvE,koKR,KR,Asia/Seoul,guldan,retail,",
	[258] = "알렉스트라자,PvE,koKR,KR,Asia/Seoul,alexstrasza,retail,",
	[264] = "말퓨리온,PvE,koKR,KR,Asia/Seoul,malfurion,retail,",
	[293] = "헬스크림,PvE,koKR,KR,Asia/Seoul,hellscream,retail,",
	[500] = "Aggramar,PvE,enGB,EU,Europe/Paris,aggramar,retail,",
	[501] = "Arathor,PvE,enGB,EU,Europe/Paris,arathor,retail,",
	[502] = "Aszune,PvE,enGB,EU,Europe/Paris,aszune,retail,",
	[503] = "Azjol-Nerub,PvE,enGB,EU,Europe/Paris,azjolnerub,retail,",
	[504] = "Bloodhoof,PvE,enGB,EU,Europe/Paris,bloodhoof,retail,",
	[505] = "Doomhammer,PvE,enGB,EU,Europe/Paris,doomhammer,retail,",
	[506] = "Draenor,PvE,enGB,EU,Europe/Paris,draenor,retail,",
	[507] = "Dragonblight,PvE,enGB,EU,Europe/Paris,dragonblight,retail,",
	[508] = "Emerald Dream,PvE,enGB,EU,Europe/Paris,emerald-dream,retail,",
	[509] = "Garona,PvE,frFR,EU,Europe/Paris,garona,retail,",
	[510] = "Vol'jin,PvE,frFR,EU,Europe/Paris,voljin,retail,",
	[511] = "Sunstrider,PvE,enGB,EU,Europe/Paris,sunstrider,retail,",
	[512] = "Arak-arahm,PvE,frFR,EU,Europe/Paris,arakarahm,retail,",
	[513] = "Twilight's Hammer,PvE,enGB,EU,Europe/Paris,twilights-hammer,retail,",
	[515] = "Zenedar,PvE,enGB,EU,Europe/Paris,zenedar,retail,",
	[516] = "Forscherliga,RP,deDE,EU,Europe/Paris,forscherliga,retail,",
	[517] = "Medivh,PvE,frFR,EU,Europe/Paris,medivh,retail,",
	[518] = "Agamaggan,PvE,enGB,EU,Europe/Paris,agamaggan,retail,",
	[519] = "Al'Akir,PvE,enGB,EU,Europe/Paris,alakir,retail,",
	[521] = "Bladefist,PvE,enGB,EU,Europe/Paris,bladefist,retail,",
	[522] = "Bloodscalp,PvE,enGB,EU,Europe/Paris,bloodscalp,retail,",
	[523] = "Burning Blade,PvE,enGB,EU,Europe/Paris,burning-blade,retail,",
	[524] = "Burning Legion,PvE,enGB,EU,Europe/Paris,burning-legion,retail,",
	[525] = "Crushridge,PvE,enGB,EU,Europe/Paris,crushridge,retail,",
	[526] = "Daggerspine,PvE,enGB,EU,Europe/Paris,daggerspine,retail,",
	[527] = "Deathwing,PvE,enGB,EU,Europe/Paris,deathwing,retail,",
	[528] = "Dragonmaw,PvE,enGB,EU,Europe/Paris,dragonmaw,retail,",
	[529] = "Dunemaul,PvE,enGB,EU,Europe/Paris,dunemaul,retail,",
	[531] = "Dethecus,PvE,deDE,EU,Europe/Paris,dethecus,retail,",
	[533] = "Sinstralis,PvE,frFR,EU,Europe/Paris,sinstralis,retail,",
	[535] = "Durotan,PvE,deDE,EU,Europe/Paris,durotan,retail,",
	[536] = "Argent Dawn,RP,enGB,EU,Europe/Paris,argent-dawn,retail,",
	[537] = "Kirin Tor,RP,frFR,EU,Europe/Paris,kirin-tor,retail,",
	[538] = "Dalaran,PvE,frFR,EU,Europe/Paris,dalaran,retail,",
	[539] = "Archimonde,PvE,frFR,EU,Europe/Paris,archimonde,retail,",
	[540] = "Elune,PvE,frFR,EU,Europe/Paris,elune,retail,",
	[541] = "Illidan,PvE,frFR,EU,Europe/Paris,illidan,retail,",
	[542] = "Hyjal,PvE,frFR,EU,Europe/Paris,hyjal,retail,",
	[543] = "Kael'thas,PvE,frFR,EU,Europe/Paris,kaelthas,retail,",
	[544] = "Ner'zhul,PvE,frFR,EU,Europe/Paris,nerzhul,retail,",
	[545] = "Cho'gall,PvE,frFR,EU,Europe/Paris,chogall,retail,",
	[546] = "Sargeras,PvE,frFR,EU,Europe/Paris,sargeras,retail,",
	[547] = "Runetotem,PvE,enGB,EU,Europe/Paris,runetotem,retail,",
	[548] = "Shadowsong,PvE,enGB,EU,Europe/Paris,shadowsong,retail,",
	[549] = "Silvermoon,PvE,enGB,EU,Europe/Paris,silvermoon,retail,",
	[550] = "Stormrage,PvE,enGB,EU,Europe/Paris,stormrage,retail,",
	[551] = "Terenas,PvE,enGB,EU,Europe/Paris,terenas,retail,",
	[552] = "Thunderhorn,PvE,enGB,EU,Europe/Paris,thunderhorn,retail,",
	[553] = "Turalyon,PvE,enGB,EU,Europe/Paris,turalyon,retail,",
	[554] = "Ravencrest,PvE,enGB,EU,Europe/Paris,ravencrest,retail,",
	[556] = "Shattered Hand,PvE,enGB,EU,Europe/Paris,shattered-hand,retail,",
	[557] = "Skullcrusher,PvE,enGB,EU,Europe/Paris,skullcrusher,retail,",
	[558] = "Spinebreaker,PvE,enGB,EU,Europe/Paris,spinebreaker,retail,",
	[559] = "Stormreaver,PvE,enGB,EU,Europe/Paris,stormreaver,retail,",
	[560] = "Stormscale,PvE,enGB,EU,Europe/Paris,stormscale,retail,",
	[561] = "Earthen Ring,RP,enGB,EU,Europe/Paris,earthen-ring,retail,",
	[562] = "Alexstrasza,PvE,deDE,EU,Europe/Paris,alexstrasza,retail,",
	[563] = "Alleria,PvE,deDE,EU,Europe/Paris,alleria,retail,",
	[564] = "Antonidas,PvE,deDE,EU,Europe/Paris,antonidas,retail,",
	[565] = "Baelgun,PvE,deDE,EU,Europe/Paris,baelgun,retail,",
	[566] = "Blackhand,PvE,deDE,EU,Europe/Paris,blackhand,retail,",
	[567] = "Gilneas,PvE,deDE,EU,Europe/Paris,gilneas,retail,",
	[568] = "Kargath,PvE,deDE,EU,Europe/Paris,kargath,retail,",
	[569] = "Khaz'goroth,PvE,deDE,EU,Europe/Paris,khazgoroth,retail,",
	[570] = "Lothar,PvE,deDE,EU,Europe/Paris,lothar,retail,",
	[571] = "Madmortem,PvE,deDE,EU,Europe/Paris,madmortem,retail,",
	[572] = "Malfurion,PvE,deDE,EU,Europe/Paris,malfurion,retail,",
	[573] = "Zuluhed,PvE,deDE,EU,Europe/Paris,zuluhed,retail,",
	[574] = "Nozdormu,PvE,deDE,EU,Europe/Paris,nozdormu,retail,",
	[575] = "Perenolde,PvE,deDE,EU,Europe/Paris,perenolde,retail,",
	[576] = "Die Silberne Hand,RP,deDE,EU,Europe/Paris,die-silberne-hand,retail,",
	[577] = "Aegwynn,PvE,deDE,EU,Europe/Paris,aegwynn,retail,",
	[578] = "Arthas,PvE,deDE,EU,Europe/Paris,arthas,retail,",
	[579] = "Azshara,PvE,deDE,EU,Europe/Paris,azshara,retail,",
	[580] = "Blackmoore,PvE,deDE,EU,Europe/Paris,blackmoore,retail,",
	[581] = "Blackrock,PvE,deDE,EU,Europe/Paris,blackrock,retail,",
	[582] = "Destromath,PvE,deDE,EU,Europe/Paris,destromath,retail,",
	[583] = "Eredar,PvE,deDE,EU,Europe/Paris,eredar,retail,",
	[584] = "Frostmourne,PvE,deDE,EU,Europe/Paris,frostmourne,retail,",
	[585] = "Frostwolf,PvE,deDE,EU,Europe/Paris,frostwolf,retail,",
	[586] = "Gorgonnash,PvE,deDE,EU,Europe/Paris,gorgonnash,retail,",
	[587] = "Gul'dan,PvE,deDE,EU,Europe/Paris,guldan,retail,",
	[588] = "Kel'Thuzad,PvE,deDE,EU,Europe/Paris,kelthuzad,retail,",
	[589] = "Kil'jaeden,PvE,deDE,EU,Europe/Paris,kiljaeden,retail,",
	[590] = "Mal'Ganis,PvE,deDE,EU,Europe/Paris,malganis,retail,",
	[591] = "Mannoroth,PvE,deDE,EU,Europe/Paris,mannoroth,retail,",
	[592] = "Zirkel des Cenarius,RP,deDE,EU,Europe/Paris,zirkel-des-cenarius,retail,",
	[593] = "Proudmoore,PvE,deDE,EU,Europe/Paris,proudmoore,retail,",
	[594] = "Nathrezim,PvE,deDE,EU,Europe/Paris,nathrezim,retail,",
	[600] = "Dun Morogh,PvE,deDE,EU,Europe/Paris,dun-morogh,retail,",
	[601] = "Aman'Thul,PvE,deDE,EU,Europe/Paris,amanthul,retail,",
	[602] = "Sen'jin,PvE,deDE,EU,Europe/Paris,senjin,retail,",
	[604] = "Thrall,PvE,deDE,EU,Europe/Paris,thrall,retail,",
	[605] = "Theradras,PvE,deDE,EU,Europe/Paris,theradras,retail,",
	[606] = "Genjuros,PvE,enGB,EU,Europe/Paris,genjuros,retail,",
	[607] = "Balnazzar,PvE,enGB,EU,Europe/Paris,balnazzar,retail,",
	[608] = "Anub'arak,PvE,deDE,EU,Europe/Paris,anubarak,retail,",
	[609] = "Wrathbringer,PvE,deDE,EU,Europe/Paris,wrathbringer,retail,",
	[610] = "Onyxia,PvE,deDE,EU,Europe/Paris,onyxia,retail,",
	[611] = "Nera'thor,PvE,deDE,EU,Europe/Paris,nerathor,retail,",
	[612] = "Nefarian,PvE,deDE,EU,Europe/Paris,nefarian,retail,",
	[613] = "Kult der Verdammten,RP,deDE,EU,Europe/Paris,kult-der-verdammten,retail,",
	[614] = "Das Syndikat,RP,deDE,EU,Europe/Paris,das-syndikat,retail,",
	[615] = "Terrordar,PvE,deDE,EU,Europe/Paris,terrordar,retail,",
	[616] = "Krag'jin,PvE,deDE,EU,Europe/Paris,kragjin,retail,",
	[617] = "Der Rat von Dalaran,RP,deDE,EU,Europe/Paris,der-rat-von-dalaran,retail,",
	[618] = "Nordrassil,PvE,enGB,EU,Europe/Paris,nordrassil,retail,",
	[619] = "Hellscream,PvE,enGB,EU,Europe/Paris,hellscream,retail,",
	[621] = "Laughing Skull,PvE,enGB,EU,Europe/Paris,laughing-skull,retail,",
	[622] = "Magtheridon,PvE,enGB,EU,Europe/Paris,magtheridon,retail,",
	[623] = "Quel'Thalas,PvE,enGB,EU,Europe/Paris,quelthalas,retail,",
	[624] = "Neptulon,PvE,enGB,EU,Europe/Paris,neptulon,retail,",
	[625] = "Twisting Nether,PvE,enGB,EU,Europe/Paris,twisting-nether,retail,",
	[626] = "Ragnaros,PvE,enGB,EU,Europe/Paris,ragnaros,retail,",
	[627] = "The Maelstrom,PvE,enGB,EU,Europe/Paris,the-maelstrom,retail,",
	[628] = "Sylvanas,PvE,enGB,EU,Europe/Paris,sylvanas,retail,",
	[629] = "Vashj,PvE,enGB,EU,Europe/Paris,vashj,retail,",
	[630] = "Bloodfeather,PvE,enGB,EU,Europe/Paris,bloodfeather,retail,",
	[631] = "Darksorrow,PvE,enGB,EU,Europe/Paris,darksorrow,retail,",
	[632] = "Frostwhisper,PvE,enGB,EU,Europe/Paris,frostwhisper,retail,",
	[633] = "Kor'gall,PvE,enGB,EU,Europe/Paris,korgall,retail,",
	[635] = "Defias Brotherhood,RP,enGB,EU,Europe/Paris,defias-brotherhood,retail,",
	[636] = "The Venture Co,RP,enGB,EU,Europe/Paris,the-venture-co,retail,",
	[637] = "Lightning's Blade,PvE,enGB,EU,Europe/Paris,lightnings-blade,retail,",
	[638] = "Haomarush,PvE,enGB,EU,Europe/Paris,haomarush,retail,",
	[639] = "Xavius,PvE,enGB,EU,Europe/Paris,xavius,retail,",
	[640] = "Khaz Modan,PvE,frFR,EU,Europe/Paris,khaz-modan,retail,",
	[641] = "Drek'Thar,PvE,frFR,EU,Europe/Paris,drekthar,retail,",
	[642] = "Rashgarroth,PvE,frFR,EU,Europe/Paris,rashgarroth,retail,",
	[643] = "Throk'Feroth,PvE,frFR,EU,Europe/Paris,throkferoth,retail,",
	[644] = "Conseil des Ombres,RP,frFR,EU,Europe/Paris,conseil-des-ombres,retail,",
	[645] = "Varimathras,PvE,frFR,EU,Europe/Paris,varimathras,retail,",
	[646] = "Hakkar,PvE,enGB,EU,Europe/Paris,hakkar,retail,",
	[647] = "Les Sentinelles,RP,frFR,EU,Europe/Paris,les-sentinelles,retail,",
	[963] = "暗影之月,PvE,zhTW,TW,Asia/Taipei,shadowmoon,retail,",
	[964] = "尖石,PvE,zhTW,TW,Asia/Taipei,spirestone,retail,",
	[965] = "雷鱗,PvE,zhTW,TW,Asia/Taipei,stormscale,retail,",
	[966] = "巨龍之喉,PvE,zhTW,TW,Asia/Taipei,dragonmaw,retail,",
	[977] = "冰霜之刺,PvE,zhTW,TW,Asia/Taipei,frostmane,retail,",
	[978] = "日落沼澤,PvE,zhTW,TW,Asia/Taipei,sundown-marsh,retail,",
	[979] = "地獄吼,PvE,zhTW,TW,Asia/Taipei,hellscream,retail,",
	[980] = "天空之牆,PvE,zhTW,TW,Asia/Taipei,skywall,retail,",
	[982] = "世界之樹,PvE,zhTW,TW,Asia/Taipei,world-tree,retail,",
	[985] = "水晶之刺,PvE,zhTW,TW,Asia/Taipei,crystalpine-stinger,retail,",
	[999] = "狂熱之刃,PvE,zhTW,TW,Asia/Taipei,zealot-blade,retail,",
	[1001] = "冰風崗哨,PvE,zhTW,TW,Asia/Taipei,chillwind-point,retail,",
	[1006] = "米奈希爾,PvE,zhTW,TW,Asia/Taipei,menethil,retail,",
	[1023] = "屠魔山谷,PvE,zhTW,TW,Asia/Taipei,demon-fall-canyon,retail,",
	[1033] = "語風,PvE,zhTW,TW,Asia/Taipei,whisperwind,retail,",
	[1037] = "血之谷,PvE,zhTW,TW,Asia/Taipei,bleeding-hollow,retail,",
	[1038] = "亞雷戈斯,PvE,zhTW,TW,Asia/Taipei,arygos,retail,",
	[1043] = "夜空之歌,PvE,zhTW,TW,Asia/Taipei,nightsong,retail,",
	[1046] = "聖光之願,PvE,zhTW,TW,Asia/Taipei,lights-hope,retail,",
	[1048] = "銀翼要塞,PvE,zhTW,TW,Asia/Taipei,silverwing-hold,retail,",
	[1049] = "憤怒使者,PvE,zhTW,TW,Asia/Taipei,wrathbringer,retail,",
	[1054] = "阿薩斯,PvE,zhTW,TW,Asia/Taipei,arthas,retail,",
	[1056] = "眾星之子,PvE,zhTW,TW,Asia/Taipei,queldorei,retail,",
	[1057] = "寒冰皇冠,PvE,zhTW,TW,Asia/Taipei,icecrown,retail,",
	[1067] = "Cho'gall,PvE,enUS,US,America/New_York,chogall,retail,",
	[1068] = "Gul'dan,PvE,enUS,US,America/New_York,guldan,retail,",
	[1069] = "Kael'thas,PvE,enUS,US,America/New_York,kaelthas,retail,",
	[1070] = "Alexstrasza,PvE,enUS,US,America/Chicago,alexstrasza,retail,",
	[1071] = "Kirin Tor,RP,enUS,US,America/Chicago,kirin-tor,retail,",
	[1072] = "Ravencrest,PvE,enUS,US,America/Chicago,ravencrest,retail,",
	[1075] = "Balnazzar,PvE,enUS,US,America/New_York,balnazzar,retail,",
	[1080] = "Khadgar,PvE,enGB,EU,Europe/Paris,khadgar,retail,",
	[1081] = "Bronzebeard,PvE,enGB,EU,Europe/Paris,bronzebeard,retail,",
	[1082] = "Kul Tiras,PvE,enGB,EU,Europe/Paris,kul-tiras,retail,",
	[1083] = "Chromaggus,PvE,enGB,EU,Europe/Paris,chromaggus,retail,",
	[1084] = "Dentarg,PvE,enGB,EU,Europe/Paris,dentarg,retail,",
	[1085] = "Moonglade,RP,enGB,EU,Europe/Paris,moonglade,retail,",
	[1086] = "La Croisade écarlate,RP,frFR,EU,Europe/Paris,la-croisade-écarlate,retail,",
	[1087] = "Executus,PvE,enGB,EU,Europe/Paris,executus,retail,",
	[1088] = "Trollbane,PvE,enGB,EU,Europe/Paris,trollbane,retail,",
	[1089] = "Mazrigos,PvE,enGB,EU,Europe/Paris,mazrigos,retail,",
	[1090] = "Talnivarr,PvE,enGB,EU,Europe/Paris,talnivarr,retail,",
	[1091] = "Emeriss,PvE,enGB,EU,Europe/Paris,emeriss,retail,",
	[1092] = "Drak'thul,PvE,enGB,EU,Europe/Paris,drakthul,retail,",
	[1093] = "Ahn'Qiraj,PvE,enGB,EU,Europe/Paris,ahnqiraj,retail,",
	[1096] = "Scarshield Legion,RP,enGB,EU,Europe/Paris,scarshield-legion,retail,",
	[1097] = "Ysera,PvE,deDE,EU,Europe/Paris,ysera,retail,",
	[1098] = "Malygos,PvE,deDE,EU,Europe/Paris,malygos,retail,",
	[1099] = "Rexxar,PvE,deDE,EU,Europe/Paris,rexxar,retail,",
	[1104] = "Anetheron,PvE,deDE,EU,Europe/Paris,anetheron,retail,",
	[1105] = "Nazjatar,PvE,deDE,EU,Europe/Paris,nazjatar,retail,",
	[1106] = "Tichondrius,PvE,deDE,EU,Europe/Paris,tichondrius,retail,",
	[1117] = "Steamwheedle Cartel,RP,enGB,EU,Europe/Paris,steamwheedle-cartel,retail,",
	[1118] = "Die ewige Wacht,RP,deDE,EU,Europe/Paris,die-ewige-wacht,retail,",
	[1119] = "Die Todeskrallen,RP,deDE,EU,Europe/Paris,die-todeskrallen,retail,",
	[1121] = "Die Arguswacht,RP,deDE,EU,Europe/Paris,die-arguswacht,retail,",
	[1122] = "Uldaman,PvE,frFR,EU,Europe/Paris,uldaman,retail,",
	[1123] = "Eitrigg,PvE,frFR,EU,Europe/Paris,eitrigg,retail,",
	[1127] = "Confrérie du Thorium,RP,frFR,EU,Europe/Paris,confrérie-du-thorium,retail,",
	[1128] = "Azshara,PvE,enUS,US,America/Chicago,azshara,retail,",
	[1129] = "Agamaggan,PvE,enUS,US,America/Chicago,agamaggan,retail,",
	[1130] = "Lightninghoof,RP,enUS,US,America/Chicago,lightninghoof,retail,",
	[1131] = "Nazjatar,PvE,enUS,US,America/Chicago,nazjatar,retail,",
	[1132] = "Malfurion,PvE,enUS,US,America/New_York,malfurion,retail,",
	[1136] = "Aegwynn,PvE,enUS,US,America/Chicago,aegwynn,retail,",
	[1137] = "Akama,PvE,enUS,US,America/Los_Angeles,akama,retail,",
	[1138] = "Chromaggus,PvE,enUS,US,America/Chicago,chromaggus,retail,",
	[1139] = "Draka,PvE,enUS,US,America/Los_Angeles,draka,retail,",
	[1140] = "Drak'thul,PvE,enUS,US,America/Los_Angeles,drakthul,retail,",
	[1141] = "Garithos,PvE,enUS,US,America/Chicago,garithos,retail,",
	[1142] = "Hakkar,PvE,enUS,US,America/Chicago,hakkar,retail,",
	[1143] = "Khaz Modan,PvE,enUS,US,America/Denver,khaz-modan,retail,",
	[1145] = "Mug'thol,PvE,enUS,US,America/Los_Angeles,mugthol,retail,",
	[1146] = "Korgath,PvE,enUS,US,America/Los_Angeles,korgath,retail,",
	[1147] = "Kul Tiras,PvE,enUS,US,America/Chicago,kul-tiras,retail,",
	[1148] = "Malorne,PvE,enUS,US,America/New_York,malorne,retail,",
	[1151] = "Rexxar,PvE,enUS,US,America/Chicago,rexxar,retail,",
	[1154] = "Thorium Brotherhood,RP,enUS,US,America/Los_Angeles,thorium-brotherhood,retail,",
	[1165] = "Arathor,PvE,enUS,US,America/Chicago,arathor,retail,",
	[1173] = "Madoran,PvE,enUS,US,America/Chicago,madoran,retail,",
	[1175] = "Trollbane,PvE,enUS,US,America/New_York,trollbane,retail,",
	[1182] = "Muradin,PvE,enUS,US,America/Denver,muradin,retail,",
	[1184] = "Vek'nilash,PvE,enUS,US,America/Chicago,veknilash,retail,",
	[1185] = "Sen'jin,PvE,enUS,US,America/Chicago,senjin,retail,",
	[1190] = "Baelgun,PvE,enUS,US,America/Los_Angeles,baelgun,retail,",
	[1258] = "Duskwood,PvE,enUS,US,America/New_York,duskwood,retail,",
	[1259] = "Zuluhed,PvE,enUS,US,America/New_York,zuluhed,retail,",
	[1260] = "Steamwheedle Cartel,RP,enUS,US,America/Chicago,steamwheedle-cartel,retail,",
	[1262] = "Norgannon,PvE,enUS,US,America/Chicago,norgannon,retail,",
	[1263] = "Thrall,PvE,enUS,US,America/New_York,thrall,retail,",
	[1264] = "Anetheron,PvE,enUS,US,America/New_York,anetheron,retail,",
	[1265] = "Turalyon,PvE,enUS,US,America/New_York,turalyon,retail,",
	[1266] = "Haomarush,PvE,enUS,US,America/Chicago,haomarush,retail,",
	[1267] = "Scilla,PvE,enUS,US,America/New_York,scilla,retail,",
	[1268] = "Ysondre,PvE,enUS,US,America/New_York,ysondre,retail,",
	[1270] = "Ysera,PvE,enUS,US,America/New_York,ysera,retail,",
	[1271] = "Dentarg,PvE,enUS,US,America/Chicago,dentarg,retail,",
	[1276] = "Andorhal,PvE,enUS,US,America/New_York,andorhal,retail,",
	[1277] = "Executus,PvE,enUS,US,America/Los_Angeles,executus,retail,",
	[1278] = "Dalvengyr,PvE,enUS,US,America/Los_Angeles,dalvengyr,retail,",
	[1280] = "Black Dragonflight,PvE,enUS,US,America/New_York,black-dragonflight,retail,",
	[1282] = "Altar of Storms,PvE,enUS,US,America/New_York,altar-of-storms,retail,",
	[1283] = "Uldaman,PvE,enUS,US,America/Chicago,uldaman,retail,",
	[1284] = "Aerie Peak,PvE,enUS,US,America/Los_Angeles,aerie-peak,retail,",
	[1285] = "Onyxia,PvE,enUS,US,America/Chicago,onyxia,retail,",
	[1286] = "Demon Soul,PvE,enUS,US,America/Los_Angeles,demon-soul,retail,",
	[1287] = "Gnomeregan,PvE,enUS,US,America/New_York,gnomeregan,retail,",
	[1288] = "Anvilmar,PvE,enUS,US,America/New_York,anvilmar,retail,",
	[1289] = "The Venture Co,RP,enUS,US,America/Chicago,the-venture-co,retail,",
	[1290] = "Sentinels,RP,enUS,US,America/Chicago,sentinels,retail,",
	[1291] = "Jaedenar,PvE,enUS,US,America/Chicago,jaedenar,retail,",
	[1292] = "Tanaris,PvE,enUS,US,America/Chicago,tanaris,retail,",
	[1293] = "Alterac Mountains,PvE,enUS,US,America/New_York,alterac-mountains,retail,",
	[1294] = "Undermine,PvE,enUS,US,America/New_York,undermine,retail,",
	[1295] = "Lethon,PvE,enUS,US,America/Chicago,lethon,retail,",
	[1296] = "Blackwing Lair,PvE,enUS,US,America/Chicago,blackwing-lair,retail,",
	[1297] = "Arygos,PvE,enUS,US,America/New_York,arygos,retail,",
	[1298] = "Vek'nilash,PvE,enGB,EU,Europe/Paris,veknilash,retail,",
	[1299] = "Boulderfist,PvE,enGB,EU,Europe/Paris,boulderfist,retail,",
	[1300] = "Frostmane,PvE,enGB,EU,Europe/Paris,frostmane,retail,",
	[1301] = "Outland,PvE,enGB,EU,Europe/Paris,outland,retail,",
	[1303] = "Grim Batol,PvE,enGB,EU,Europe/Paris,grim-batol,retail,",
	[1304] = "Jaedenar,PvE,enGB,EU,Europe/Paris,jaedenar,retail,",
	[1305] = "Kazzak,PvE,enGB,EU,Europe/Paris,kazzak,retail,",
	[1306] = "Tarren Mill,PvE,enGB,EU,Europe/Paris,tarren-mill,retail,",
	[1307] = "Chamber of Aspects,PvE,enGB,EU,Europe/Paris,chamber-of-aspects,retail,",
	[1308] = "Ravenholdt,RP,enGB,EU,Europe/Paris,ravenholdt,retail,",
	[1309] = "Pozzo dell'Eternità,PvE,itIT,EU,Europe/Paris,pozzo-delleternità,retail,",
	[1310] = "Eonar,PvE,enGB,EU,Europe/Paris,eonar,retail,",
	[1311] = "Kilrogg,PvE,enGB,EU,Europe/Paris,kilrogg,retail,",
	[1312] = "Aerie Peak,PvE,enGB,EU,Europe/Paris,aerie-peak,retail,",
	[1313] = "Wildhammer,PvE,enGB,EU,Europe/Paris,wildhammer,retail,",
	[1314] = "Saurfang,PvE,enGB,EU,Europe/Paris,saurfang,retail,",
	[1316] = "Nemesis,PvE,itIT,EU,Europe/Paris,nemesis,retail,",
	[1317] = "Darkmoon Faire,RP,enGB,EU,Europe/Paris,darkmoon-faire,retail,",
	[1318] = "Vek'lor,PvE,deDE,EU,Europe/Paris,veklor,retail,",
	[1319] = "Mug'thol,PvE,deDE,EU,Europe/Paris,mugthol,retail,",
	[1320] = "Taerar,PvE,deDE,EU,Europe/Paris,taerar,retail,",
	[1321] = "Dalvengyr,PvE,deDE,EU,Europe/Paris,dalvengyr,retail,",
	[1322] = "Rajaxx,PvE,deDE,EU,Europe/Paris,rajaxx,retail,",
	[1323] = "Ulduar,PvE,deDE,EU,Europe/Paris,ulduar,retail,",
	[1324] = "Malorne,PvE,deDE,EU,Europe/Paris,malorne,retail,",
	[1326] = "Der abyssische Rat,RP,deDE,EU,Europe/Paris,der-abyssische-rat,retail,",
	[1327] = "Der Mithrilorden,RP,deDE,EU,Europe/Paris,der-mithrilorden,retail,",
	[1328] = "Tirion,PvE,deDE,EU,Europe/Paris,tirion,retail,",
	[1330] = "Ambossar,PvE,deDE,EU,Europe/Paris,ambossar,retail,",
	[1331] = "Suramar,PvE,frFR,EU,Europe/Paris,suramar,retail,",
	[1332] = "Krasus,PvE,frFR,EU,Europe/Paris,krasus,retail,",
	[1333] = "Die Nachtwache,RP,deDE,EU,Europe/Paris,die-nachtwache,retail,",
	[1334] = "Arathi,PvE,frFR,EU,Europe/Paris,arathi,retail,",
	[1335] = "Ysondre,PvE,frFR,EU,Europe/Paris,ysondre,retail,",
	[1336] = "Eldre'Thalas,PvE,frFR,EU,Europe/Paris,eldrethalas,retail,",
	[1337] = "Culte de la Rive noire,RP,frFR,EU,Europe/Paris,culte-de-la-rive-noire,retail,",
	[1342] = "Echo Isles,PvE,enUS,US,America/Los_Angeles,echo-isles,retail,",
	[1344] = "The Forgotten Coast,PvE,enUS,US,America/New_York,the-forgotten-coast,retail,",
	[1345] = "Fenris,PvE,enUS,US,America/Los_Angeles,fenris,retail,",
	[1346] = "Anub'arak,PvE,enUS,US,America/Chicago,anubarak,retail,",
	[1347] = "Blackwater Raiders,RP,enUS,US,America/Denver,blackwater-raiders,retail,",
	[1348] = "Vashj,PvE,enUS,US,America/New_York,vashj,retail,",
	[1349] = "Korialstrasz,PvE,enUS,US,America/Los_Angeles,korialstrasz,retail,",
	[1350] = "Misha,PvE,enUS,US,America/Chicago,misha,retail,",
	[1351] = "Darrowmere,PvE,enUS,US,America/Los_Angeles,darrowmere,retail,",
	[1352] = "Ravenholdt,RP,enUS,US,America/Chicago,ravenholdt,retail,",
	[1353] = "Bladefist,PvE,enUS,US,America/Chicago,bladefist,retail,",
	[1354] = "Shu'halo,PvE,enUS,US,America/Chicago,shuhalo,retail,",
	[1355] = "Winterhoof,PvE,enUS,US,America/Los_Angeles,winterhoof,retail,",
	[1356] = "Sisters of Elune,RP,enUS,US,America/Denver,sisters-of-elune,retail,",
	[1357] = "Maiev,PvE,enUS,US,America/Chicago,maiev,retail,",
	[1358] = "Rivendare,PvE,enUS,US,America/New_York,rivendare,retail,",
	[1359] = "Nordrassil,PvE,enUS,US,America/Denver,nordrassil,retail,",
	[1360] = "Tortheldrin,PvE,enUS,US,America/Los_Angeles,tortheldrin,retail,",
	[1361] = "Cairne,PvE,enUS,US,America/Los_Angeles,cairne,retail,",
	[1362] = "Drak'Tharon,PvE,enUS,US,America/New_York,draktharon,retail,",
	[1363] = "Antonidas,PvE,enUS,US,America/Los_Angeles,antonidas,retail,",
	[1364] = "Shandris,PvE,enUS,US,America/Los_Angeles,shandris,retail,",
	[1365] = "Moon Guard,RP,enUS,US,America/Chicago,moon-guard,retail,",
	[1367] = "Nazgrel,PvE,enUS,US,America/Chicago,nazgrel,retail,",
	[1368] = "Hydraxis,PvE,enUS,US,America/Los_Angeles,hydraxis,retail,",
	[1369] = "Wyrmrest Accord,RP,enUS,US,America/Los_Angeles,wyrmrest-accord,retail,",
	[1370] = "Farstriders,RP,enUS,US,America/Los_Angeles,farstriders,retail,",
	[1371] = "Borean Tundra,PvE,enUS,US,America/Los_Angeles,borean-tundra,retail,",
	[1372] = "Quel'dorei,PvE,enUS,US,America/Chicago,queldorei,retail,",
	[1373] = "Garrosh,PvE,enUS,US,America/Chicago,garrosh,retail,",
	[1374] = "Mok'Nathal,PvE,enUS,US,America/Los_Angeles,moknathal,retail,",
	[1375] = "Nesingwary,PvE,enUS,US,America/Chicago,nesingwary,retail,",
	[1377] = "Drenden,PvE,enUS,US,America/Chicago,drenden,retail,",
	[1378] = "Dun Modr,PvE,esES,EU,Europe/Paris,dun-modr,retail,",
	[1379] = "Zul'jin,PvE,esES,EU,Europe/Paris,zuljin,retail,",
	[1380] = "Uldum,PvE,esES,EU,Europe/Paris,uldum,retail,",
	[1381] = "C'Thun,PvE,esES,EU,Europe/Paris,cthun,retail,",
	[1382] = "Sanguino,PvE,esES,EU,Europe/Paris,sanguino,retail,",
	[1383] = "Shen'dralar,PvE,esES,EU,Europe/Paris,shendralar,retail,",
	[1384] = "Tyrande,PvE,esES,EU,Europe/Paris,tyrande,retail,",
	[1385] = "Exodar,PvE,esES,EU,Europe/Paris,exodar,retail,",
	[1386] = "Minahonda,PvE,esES,EU,Europe/Paris,minahonda,retail,",
	[1387] = "Los Errantes,PvE,esES,EU,Europe/Paris,los-errantes,retail,",
	[1388] = "Lightbringer,PvE,enGB,EU,Europe/Paris,lightbringer,retail,",
	[1389] = "Darkspear,PvE,enGB,EU,Europe/Paris,darkspear,retail,",
	[1391] = "Alonsus,PvE,enGB,EU,Europe/Paris,alonsus,retail,",
	[1392] = "Burning Steppes,PvE,enGB,EU,Europe/Paris,burning-steppes,retail,",
	[1393] = "Bronze Dragonflight,PvE,enGB,EU,Europe/Paris,bronze-dragonflight,retail,",
	[1394] = "Anachronos,PvE,enGB,EU,Europe/Paris,anachronos,retail,",
	[1395] = "Colinas Pardas,PvE,esES,EU,Europe/Paris,colinas-pardas,retail,Spirestone",
	[1400] = "Un'Goro,PvE,deDE,EU,Europe/Paris,ungoro,retail,",
	[1401] = "Garrosh,PvE,deDE,EU,Europe/Paris,garrosh,retail,",
	[1404] = "Area 52,PvE,deDE,EU,Europe/Paris,area-52,retail,",
	[1405] = "Todeswache,RP,deDE,EU,Europe/Paris,todeswache,retail,",
	[1406] = "Arygos,PvE,deDE,EU,Europe/Paris,arygos,retail,",
	[1407] = "Teldrassil,PvE,deDE,EU,Europe/Paris,teldrassil,retail,",
	[1408] = "Norgannon,PvE,deDE,EU,Europe/Paris,norgannon,retail,",
	[1409] = "Lordaeron,PvE,deDE,EU,Europe/Paris,lordaeron,retail,",
	[1413] = "Aggra (Português),PvE,ptPT,EU,Europe/Paris,aggra-português,retail,",
	[1415] = "Terokkar,PvE,enGB,EU,Europe/Paris,terokkar,retail,",
	[1416] = "Blade's Edge,PvE,enGB,EU,Europe/Paris,blades-edge,retail,",
	[1417] = "Azuremyst,PvE,enGB,EU,Europe/Paris,azuremyst,retail,",
	[1425] = "Drakkari,PvE,esMX,US,America/Chicago,drakkari,retail,",
	[1427] = "Ragnaros,PvE,esMX,US,America/Chicago,ragnaros,retail,",
	[1428] = "Quel'Thalas,PvE,esMX,US,America/Chicago,quelthalas,retail,",
	[1549] = "Azuremyst,PvE,enUS,US,America/Chicago,azuremyst,retail,",
	[1555] = "Auchindoun,PvE,enUS,US,America/New_York,auchindoun,retail,",
	[1556] = "Coilfang,PvE,enUS,US,America/Los_Angeles,coilfang,retail,",
	[1557] = "Shattered Halls,PvE,enUS,US,America/Los_Angeles,shattered-halls,retail,",
	[1558] = "Blood Furnace,PvE,enUS,US,America/Chicago,blood-furnace,retail,",
	[1559] = "The Underbog,PvE,enUS,US,America/Chicago,the-underbog,retail,",
	[1563] = "Terokkar,PvE,enUS,US,America/Chicago,terokkar,retail,",
	[1564] = "Blade's Edge,PvE,enUS,US,America/Chicago,blades-edge,retail,",
	[1565] = "Exodar,PvE,enUS,US,America/Chicago,exodar,retail,",
	[1566] = "Area 52,PvE,enUS,US,America/New_York,area-52,retail,",
	[1567] = "Velen,PvE,enUS,US,America/New_York,velen,retail,",
	[1570] = "The Scryers,RP,enUS,US,America/New_York,the-scryers,retail,",
	[1572] = "Zangarmarsh,PvE,enUS,US,America/Chicago,zangarmarsh,retail,",
	[1576] = "Fizzcrank,PvE,enUS,US,America/Chicago,fizzcrank,retail,",
	[1578] = "Ghostlands,PvE,enUS,US,America/New_York,ghostlands,retail,",
	[1579] = "Grizzly Hills,PvE,enUS,US,America/New_York,grizzly-hills,retail,",
	[1581] = "Galakrond,PvE,enUS,US,America/Chicago,galakrond,retail,",
	[1582] = "Dawnbringer,PvE,enUS,US,America/Chicago,dawnbringer,retail,",
	[1587] = "Hellfire,PvE,enGB,EU,Europe/Paris,hellfire,retail,",
	[1588] = "Ghostlands,PvE,enGB,EU,Europe/Paris,ghostlands,retail,",
	[1589] = "Nagrand,PvE,enGB,EU,Europe/Paris,nagrand,retail,",
	[1595] = "The Sha'tar,RP,enGB,EU,Europe/Paris,the-shatar,retail,",
	[1596] = "Karazhan,PvE,enGB,EU,Europe/Paris,karazhan,retail,",
	[1597] = "Auchindoun,PvE,enGB,EU,Europe/Paris,auchindoun,retail,",
	[1598] = "Shattered Halls,PvE,enGB,EU,Europe/Paris,shattered-halls,retail,",
	[1602] = "Gordunni,PvE,ruRU,EU,Europe/Paris,gordunni,retail,Гордунни",
	[1603] = "Lich King,PvE,ruRU,EU,Europe/Paris,lich-king,retail,Король-лич",
	[1604] = "Soulflayer,PvE,ruRU,EU,Europe/Paris,soulflayer,retail,Свежеватель Душ",
	[1605] = "Deathguard,PvE,ruRU,EU,Europe/Paris,deathguard,retail,Страж Смерти",
	[1606] = "Sporeggar,RP,enGB,EU,Europe/Paris,sporeggar,retail,",
	[1607] = "Nethersturm,PvE,deDE,EU,Europe/Paris,nethersturm,retail,",
	[1608] = "Shattrath,PvE,deDE,EU,Europe/Paris,shattrath,retail,",
	[1609] = "Deepholm,PvE,ruRU,EU,Europe/Paris,deepholm,retail,Подземье",
	[1610] = "Greymane,PvE,ruRU,EU,Europe/Paris,greymane,retail,Седогрив",
	[1611] = "Festung der Stürme,PvE,deDE,EU,Europe/Paris,festung-der-stürme,retail,",
	[1612] = "Echsenkessel,PvE,deDE,EU,Europe/Paris,echsenkessel,retail,",
	[1613] = "Blutkessel,PvE,deDE,EU,Europe/Paris,blutkessel,retail,",
	[1614] = "Galakrond,PvE,ruRU,EU,Europe/Paris,galakrond,retail,Галакронд",
	[1615] = "Howling Fjord,PvE,ruRU,EU,Europe/Paris,howling-fjord,retail,Ревущий фьорд",
	[1616] = "Razuvious,PvE,ruRU,EU,Europe/Paris,razuvious,retail,Разувий",
	[1617] = "Deathweaver,PvE,ruRU,EU,Europe/Paris,deathweaver,retail,Ткач Смерти",
	[1618] = "Die Aldor,RP,deDE,EU,Europe/Paris,die-aldor,retail,",
	[1619] = "Das Konsortium,RP,deDE,EU,Europe/Paris,das-konsortium,retail,",
	[1620] = "Chants éternels,PvE,frFR,EU,Europe/Paris,chants-éternels,retail,",
	[1621] = "Marécage de Zangar,PvE,frFR,EU,Europe/Paris,marécage-de-zangar,retail,",
	[1622] = "Temple noir,PvE,frFR,EU,Europe/Paris,temple-noir,retail,",
	[1623] = "Fordragon,PvE,ruRU,EU,Europe/Paris,fordragon,retail,Дракономор",
	[1624] = "Naxxramas,PvE,frFR,EU,Europe/Paris,naxxramas,retail,",
	[1625] = "Borean Tundra,PvE,ruRU,EU,Europe/Paris,borean-tundra,retail,Борейская тундра",
	[1626] = "Les Clairvoyants,RP,frFR,EU,Europe/Paris,les-clairvoyants,retail,",
	[1922] = "Azuregos,PvE,ruRU,EU,Europe/Paris,azuregos,retail,Азурегос",
	[1923] = "Ashenvale,PvE,ruRU,EU,Europe/Paris,ashenvale,retail,Ясеневый лес",
	[1924] = "Booty Bay,PvE,ruRU,EU,Europe/Paris,booty-bay,retail,Пиратская Бухта",
	[1925] = "Eversong,PvE,ruRU,EU,Europe/Paris,eversong,retail,Вечная Песня",
	[1926] = "Thermaplugg,PvE,ruRU,EU,Europe/Paris,thermaplugg,retail,Термоштепсель",
	[1927] = "Grom,PvE,ruRU,EU,Europe/Paris,grom,retail,Гром",
	[1928] = "Goldrinn,PvE,ruRU,EU,Europe/Paris,goldrinn,retail,Голдринн",
	[1929] = "Blackscar,PvE,ruRU,EU,Europe/Paris,blackscar,retail,Черный Шрам",
	[2075] = "雲蛟衛,PvE,zhTW,TW,Asia/Taipei,order-of-the-cloud-serpent,retail,",
	[2079] = "와일드해머,PvE,koKR,KR,Asia/Seoul,wildhammer,retail,",
	[2106] = "렉사르,PvE,koKR,KR,Asia/Seoul,rexxar,retail,",
	[2107] = "하이잘,PvE,koKR,KR,Asia/Seoul,hyjal,retail,",
	[2108] = "데스윙,PvE,koKR,KR,Asia/Seoul,deathwing,retail,",
	[2110] = "세나리우스,PvE,koKR,KR,Asia/Seoul,cenarius,retail,",
	[2111] = "스톰레이지,PvE,koKR,KR,Asia/Seoul,stormrage,retail,",
	[2116] = "줄진,PvE,koKR,KR,Asia/Seoul,zuljin,retail,",
	[3207] = "Goldrinn,PvE,ptBR,US,America/Sao_Paulo,goldrinn,retail,",
	[3208] = "Nemesis,PvE,ptBR,US,America/Sao_Paulo,nemesis,retail,",
	[3209] = "Azralon,PvE,ptBR,US,America/Sao_Paulo,azralon,retail,",
	[3210] = "Tol Barad,PvE,ptBR,US,America/Sao_Paulo,tol-barad,retail,",
	[3234] = "Gallywix,PvE,ptBR,US,America/Sao_Paulo,gallywix,retail,",
	[3721] = "Caelestrasz,PvE,enUS,US,Australia/Melbourne,caelestrasz,retail,",
	[3722] = "Aman'Thul,PvE,enUS,US,Australia/Melbourne,amanthul,retail,",
	[3723] = "Barthilas,PvE,enUS,US,Australia/Melbourne,barthilas,retail,",
	[3724] = "Thaurissan,PvE,enUS,US,Australia/Melbourne,thaurissan,retail,",
	[3725] = "Frostmourne,PvE,enUS,US,Australia/Melbourne,frostmourne,retail,",
	[3726] = "Khaz'goroth,PvE,enUS,US,Australia/Melbourne,khazgoroth,retail,",
	[3733] = "Dreadmaul,PvE,enUS,US,Australia/Melbourne,dreadmaul,retail,",
	[3734] = "Nagrand,PvE,enUS,US,Australia/Melbourne,nagrand,retail,",
	[3735] = "Dath'Remar,PvE,enUS,US,Australia/Melbourne,dathremar,retail,",
	[3736] = "Jubei'Thos,PvE,enUS,US,Australia/Melbourne,jubeithos,retail,",
	[3737] = "Gundrak,PvE,enUS,US,Australia/Melbourne,gundrak,retail,",
	[3738] = "Saurfang,PvE,enUS,US,Australia/Melbourne,saurfang,retail,",
	[5735] = "克羅之刃,PvE,zhTW,TW,Asia/Taipei,krol-blade,retail,",
	[5736] = "老馬布蘭契,PvE,zhTW,TW,Asia/Taipei,old-blanchy,retail,",
}

local rawConnectionData = {
	"EU,504,1080",
	"EU,1084,1306",
	"EU,507,527,627,637,1588,1596",
	"EU,529,628,1304,1597",
	"EU,511,526,607,621,1083,1088,1090,1093,1299,1598",
	"EU,1602",
	"EU,1604",
	"EU,1605",
	"EU,1609,1614,1616",
	"EU,568,604,1330",
	"EU,513,518,522,525,646,1091",
	"EU,523,1092",
	"EU,1097,1324",
	"EU,572,1098",
	"EU,587,589,594,1104,1322,1611",
	"EU,573,584,601,608,1105,1321",
	"EU,576,613,614,1118,1119,1121,1326,1619",
	"EU,641,1122,1123,1332",
	"EU,537,644,647,1086,1127,1337,1626",
	"EU,505,553",
	"EU,1081,1298,1310,1312,1416",
	"EU,531,605,610,615,1319",
	"EU,510,1620",
	"EU,512,543,642,643",
	"EU,567,582,586,591,611,612,1323",
	"EU,556,630,633,1087,1314,1389,1392,1415",
	"EU,517,1331",
	"EU,574,575,1401,1407,1608",
	"EU,506",
	"EU,569,1406",
	"EU,533,538,545,1336,1621",
	"EU,541,1334,1622,1624",
	"EU,535,578,588,609,1318,1328,1613",
	"EU,580,1106,1409",
	"EU,1615",
	"EU,1307",
	"EU,1309",
	"EU,581",
	"EU,509,544,546",
	"EU,500,619",
	"EU,554",
	"EU,1335",
	"EU,552,1313",
	"EU,1316",
	"EU,1623",
	"EU,565,570,579,616",
	"EU,561,635,636,1096,1308,1317,1606",
	"EU,1082,1391,1394",
	"EU,1378,1381",
	"EU,1379,1380,1382,1383",
	"EU,1384,1387,1395",
	"EU,1385,1386",
	"EU,1089,1388",
	"EU,618,1393",
	"EU,503,623",
	"EU,602,1400,1404",
	"EU,563,1099",
	"EU,1618",
	"EU,542",
	"EU,1925",
	"EU,1603,1610,1928",
	"EU,1617,1625,1924,1926,1927,1929",
	"EU,516,592,617,1327,1333,1405",
	"EU,550,1417",
	"EU,560",
	"EU,508,551",
	"EU,539",
	"EU,1300,1303,1413",
	"EU,1305",
	"EU,1085,1117,1595",
	"EU,540,645",
	"EU,501,547,1311,1587,1589",
	"EU,1301",
	"EU,1922",
	"EU,1923",
	"EU,600,1408",
	"EU,549",
	"EU,528,558,559,629,638",
	"EU,515,521,606,624,631,632",
	"EU,502,548",
	"EU,536",
	"EU,585",
	"EU,519,524,557,639",
	"EU,625",
	"EU,577",
	"EU,622",
	"EU,626",
	"EU,564",
	"EU,640",
	"EU,566,590,1320,1612",
	"EU,583",
	"EU,562,571,593,1607",
	"US,10,121,1143,1182,1359",
	"US,7,110,124,127,1148,1348,1358,1362",
	"US,3,151",
	"US,115,1342",
	"US,106,1576",
	"US,1072,1283",
	"US,58",
	"US,67,97,101,1067,1555",
	"US,73",
	"US,68,153,1069,1132,1175,1287,1578,1579",
	"US,1184,1367,1375",
	"US,108,111,112,119,1185,1357,1372",
	"US,75,1570",
	"US,84,116,123,1137,1145,1349,1363",
	"US,85,86,90,131,1140,1368,1371,1374",
	"US,74,96,156,1068,1259,1267,1276,1280,1567",
	"US,99,1297",
	"US,100",
	"US,14,51,91,95,104,1285",
	"US,114,1345",
	"US,53,82,92,93,159,1572",
	"US,4,1355",
	"US,47,1354",
	"US,118,126",
	"US,5",
	"US,12,1154,1370",
	"US,2,8,122,128,1146,1360,1361",
	"US,1369",
	"US,83,109,129,1136,1142,1373",
	"US,162",
	"US,54,1581",
	"US,55,1271",
	"US,60",
	"US,63,1270",
	"US,64,1258",
	"US,1151,1350",
	"US,160,1173,1549,1582",
	"US,57",
	"US,76",
	"US,70,77,79,103,1128,1131,1558",
	"US,78,1264,1268,1282",
	"US,1425",
	"US,1284",
	"US,1427",
	"US,88,125,1347,1356",
	"US,1070,1563",
	"US,1071,1260,1290",
	"US,1147,1353",
	"US,61",
	"US,163,164,1130,1289,1352",
	"US,15,155,1277,1557",
	"US,72,157,1278,1286,1556",
	"US,56,98,102,105,1129,1262,1291,1559,1564",
	"US,13,1190",
	"US,11",
	"US,87,113,1139,1351",
	"US,52,62,65,1565",
	"US,69",
	"US,81,94,154,1266,1295,1296",
	"US,3234",
	"US,158,1292",
	"US,9",
	"US,120",
	"US,117,1364",
	"US,89,107,130,1138,1141,1165,1346,1377",
	"US,71,80,1075,1288,1293,1294,1344",
	"US,1428",
	"US,3207",
	"US,3208,3210",
	"US,3209",
	"US,66",
	"US,59",
	"US,1265",
	"US,1365",
	"US,1566",
	"US,1263",
	"US,6",
	"US,16",
	"US,1",
	"US,3721,3734,3738",
	"US,3723",
	"US,3724,3725,3733,3736,3737",
	"US,3722,3726,3735",
	"KR,205",
	"KR,201,210,2111",
	"KR,214,258,2079,2106,2108",
	"KR,207,211,212,215,264,293,2107,2110,2116",
	"TW,963,964,979,999,1001,1033,1054,1056,1057",
	"TW,965,966,977,982,1006,1037,1038,1043,2075",
	"TW,978,980,985,1023,1046,1048,1049",
	"TW,5735",
	"TW,5736",
}

local unpacked
local currentRegion
local realmsByRegionAndName = {}

local function copyList(list)
	if type(list) ~= "table" then return nil end
	local copy = {}
	for i = 1, #list do
		copy[i] = list[i]
	end
	return copy
end

local function getNameForAPI(name)
	if not name then return nil end
	name = tostring(name):lower()
	return (name:gsub("[%s%-']", ""):gsub("`", ""):gsub("´", ""):gsub("’", ""))
end

local function cloneRealm(realm)
	if type(realm) ~= "table" then return nil end
	return {
		id = realm.id,
		name = realm.name,
		nameForAPI = realm.nameForAPI,
		rules = realm.rules,
		locale = realm.locale,
		region = realm.region,
		timezone = realm.timezone,
		utc = realm.utc,
		connections = copyList(realm.connections),
		englishName = realm.englishName,
		englishNameForAPI = realm.englishNameForAPI,
		gameClient = realm.gameClient,
		fallback = realm.fallback,
	}
end

local function getFallbackRegion()
	if currentRegion then return currentRegion end
	local regionID = GetCurrentRegion and GetCurrentRegion()
	currentRegion = ({ "US", "KR", "EU", "TW", "CN" })[regionID] or "US"
	return currentRegion
end

local function unpackData()
	if unpacked then return end
	for id, info in pairs(rawRealmData) do
		local name, rules, locale, region, timezone, englishName, gameClient, aliases = strsplit(",", info)
		rawRealmData[id] = {
			id = id,
			name = name,
			nameForAPI = getNameForAPI(name),
			rules = rules and string.upper(rules) or nil,
			locale = locale,
			region = region,
			timezone = timezone,
			utc = timezone2utc[timezone],
			englishName = englishName,
			englishNameForAPI = getNameForAPI(englishName),
			gameClient = gameClient,
		}
		if region then
			realmsByRegionAndName[region] = realmsByRegionAndName[region] or {}
			if rawRealmData[id].nameForAPI then realmsByRegionAndName[region][rawRealmData[id].nameForAPI] = id end
			if rawRealmData[id].englishNameForAPI then realmsByRegionAndName[region][rawRealmData[id].englishNameForAPI] = id end
			if aliases and aliases ~= "" then
				for _, alias in ipairs({ strsplit(";", aliases) }) do
					local aliasNameForAPI = getNameForAPI(alias)
					if aliasNameForAPI then realmsByRegionAndName[region][aliasNameForAPI] = id end
				end
			end
		end
	end
	for _, connectedRealmsStr in ipairs(rawConnectionData) do
		local connectedRealms = { strsplit(",", connectedRealmsStr) }
		table.remove(connectedRealms, 1)
		for i = 1, #connectedRealms do
			connectedRealms[i] = tonumber(connectedRealms[i]) or connectedRealms[i]
		end
		for _, id in ipairs(connectedRealms) do
			local realm = rawRealmData[id]
			if realm then realm.connections = connectedRealms end
		end
	end
	unpacked = true
end

local function getCurrentRegionFromGUID()
	if currentRegion then return currentRegion end
	unpackData()
	local guid = UnitGUID and UnitGUID("player")
	if guid then
		local server = tonumber(strmatch(guid, "^Player%-(%d+)"))
		local realm = server and rawRealmData[server]
		if realm and realm.region then
			currentRegion = realm.region
			return currentRegion
		end
	end
	return getFallbackRegion()
end

local function findRealm(name, region)
	if type(name) ~= "string" or name == "" then return nil end
	local apiName = getNameForAPI(strtrim(name))
	if not apiName or apiName == "" then return nil end
	region = region or getCurrentRegionFromGUID()
	local regionIndex = realmsByRegionAndName[region]
	local id = regionIndex and regionIndex[apiName]
	return id and rawRealmData[id] or nil
end

local function addAutoCompleteFallbacks(region)
	local getAutoCompleteRealms = C_AutoComplete and C_AutoComplete.GetAutoCompleteRealms or GetAutoCompleteRealms
	if not getAutoCompleteRealms then return end
	local names = getAutoCompleteRealms()
	if type(names) ~= "table" or #names == 0 then return end
	region = region or getCurrentRegionFromGUID()
	local connections = {}
	for _, name in ipairs(names) do
		local realm = findRealm(name, region)
		if realm then
			connections[#connections + 1] = realm.id
		else
			local apiName = getNameForAPI(name)
			local id = "auto:" .. apiName
			if not rawRealmData[id] then
				rawRealmData[id] = {
					id = id,
					name = name,
					nameForAPI = apiName,
					rules = "PVE",
					locale = GetLocale and GetLocale() or "enUS",
					region = region,
					fallback = true,
				}
				realmsByRegionAndName[region] = realmsByRegionAndName[region] or {}
				realmsByRegionAndName[region][apiName] = id
			end
			connections[#connections + 1] = id
		end
	end
	if #connections == 0 then return end
	for _, id in ipairs(connections) do
		local realm = rawRealmData[id]
		if realm and not realm.connections then realm.connections = connections end
	end
end

function realmInfo.GetCurrentRegion()
	return getCurrentRegionFromGUID()
end

function realmInfo.GetRealmInfo(name, region)
	unpackData()
	if type(name) == "number" or (type(name) == "string" and name:match("^%d+$")) then return realmInfo.GetRealmInfoByID(name) end
	local realm = findRealm(name, region)
	if not realm then
		addAutoCompleteFallbacks(region)
		realm = findRealm(name, region)
	end
	return cloneRealm(realm)
end

function realmInfo.GetRealmInfoByID(id)
	unpackData()
	id = tonumber(id) or id
	return cloneRealm(rawRealmData[id])
end

function realmInfo.GetConnectionNames(realm)
	unpackData()
	if type(realm) ~= "table" or type(realm.connections) ~= "table" then return nil end
	local names = {}
	for _, id in ipairs(realm.connections) do
		local connectedRealm = rawRealmData[tonumber(id) or id]
		if connectedRealm and connectedRealm.name then names[#names + 1] = connectedRealm.name end
	end
	if #names == 0 then return nil end
	table.sort(names)
	return names
end

function realmInfo.GetRealmFromNameString(value)
	if type(value) ~= "string" then return GetRealmName and GetRealmName() or nil end
	local _, realm = strsplit("-", value, 2)
	if realm and realm ~= "" then return realm end
	return GetRealmName and GetRealmName() or nil
end

function realmInfo.FormatRealmType(realm)
	local rules = realm and realm.rules
	if type(rules) ~= "string" or rules == "" then return nil end
	local lower = rules:lower()
	if lower == "rp" or lower == "rppvp" then return "RP PvE" end
	if lower == "pvp" then return "PvE" end
	return rules:gsub("V", "v")
end

function realmInfo.FormatRealmTimezone(realm)
	if type(realm) ~= "table" then return nil end
	local utc = realm.utc or timezone2utc[realm.timezone]
	if not utc then return realm.timezone end
	if utc == 0 then return "UTC" end
	return "UTC" .. (utc > 0 and "+" or "") .. tostring(utc)
end
