local _, namespace = ...

local L = setmetatable({}, { __index = function(t, k)
    local v = tostring(k)
    rawset(t, k, v)
    return v
end })

namespace.L = L

local LOCALE = GetLocale()

if LOCALE == "enUS" then
    -- English
return end

if LOCALE == "deDE" then
    -- German
    L["Battleground Blitz"] = "Blitzschlachtfeld"
    L["Solo Shuffle"] = "Gemischtes Einzel"
    L["Warsong Gulch"] = "Kriegshymnenschlucht"
    L["Twin Peaks"] = "Zwillingsgipfel"
    L["The Battle for Gilneas"] = "Schlacht um Gilneas"
    L["Eye of the Sorm"] = "Auge des Sturms"
    L["Rated Eye of the Storm"] = "Gew. Auge des Sturms"
    L["Temple of Kotmogu"] = "Tempel von Katmogu"
    L["Silvershard Mines"] = "Silberbruchmine"
    L["Seething Shore"] = "Brodelnde Küste"
    L["Arathi Basin"] = "Arathibecken"
    L["Deepwind Gorge"] = "Tiefenwindschlucht"
    L["Deepwind Gorge (Legacy)"] = "Tiefenwindschlucht (Klassisch)"
    L["Alterac Valley"] = "Alteractal"
    L["Isle of Conquest"] = "Insel der Eroberung"
    L["Battle for Wintergrasp"] = "Schlacht um Tausendwinter"
    L["Ashran"] = "Ashran"
    L["Classic Ashran"] = "Klassisches Ashran"
    L["Slayer's Rise"] = "Schlächteranhöhe"
    L["Strand of the Ancients"] = "Strand der Uralten"
    L["Deephaul Ravine"] = "Tiefbeuteschlucht"
    L["Ruins of Lordaeron"] = "Ruinen von Lordaeron"
    L["Dalaran Sewers"] = "Kanalisation von Dalaran"
    L["Tol'Viron Arena"] = "Arena der Tol'vir"
    L["The Tiger's Peak"] = "Tigergipfel"
    L["Black Rook Hold Arena"] = "Arena der Rabenwehr"
    L["Nagrand Arena"] = "Arena von Nagrand"
    L["Ashamane's Fall"] = "Ashamanes Sturz"
    L["Blade's Edge Arena"] = "Arena des Schergrats"
    L["Hook Point"] = "Hakenkap"
    L["Mugambala"] = "Mugambala"
    L["The Robodrome"] = "Das Robodrom"
    L["Empyrean Domain"] = "Emyriumdomäne"
    L["Maldraxxus Coliseum"] = "Kolosseum von Maldraxxus"
    L["Enigma Crucible"] = "Enigmatiegel"
    L["Nokhudon Proving Grounds"] = "Feuerprobe von Nokhudon"
    L["Cage of Carnage"] = "Käfig des Gemetzels"
    L["All Arenas"] = "Alle Arenen"
return end

if LOCALE == "esES" then
    -- Spanish (EU)
    L["Battleground Blitz"] = "Campo de batalla relámpago"
    L["Solo Shuffle"] = "Batiburrillo de solitarios"
    L["Warsong Gulch"] = "Garganta Grito de Guerra"
    L["Twin Peaks"] = "Cumbres Gemelas"
    L["The Battle for Gilneas"] = "La Batalla por Gilneas"
    L["Eye of the Sorm"] = "Ojo de la Tormenta"
    L["Rated Eye of the Storm"] = "Ojo de la Tormenta puntuado"
    L["Temple of Kotmogu"] = "Templo de Kotmogu"
    L["Silvershard Mines"] = "Minas Lonjaplata"
    L["Seething Shore"] = "Costa Hirviente"
    L["Arathi Basin"] = "Cuenca de Arathi"
    L["Deepwind Gorge"] = "Cañón del Céfiro"
    L["Deepwind Gorge (Legacy)"] = "Cañón del Céfiro (antiguo)"
    L["Alterac Valley"] = "Valle de Alterac"
    L["Isle of Conquest"] = "Isla de la Conquista"
    L["Battle for Wintergrasp"] = "Batalla por Conquista del Invierno"
    L["Ashran"] = "Ashran"
    L["Classic Ashran"] = "Ashran clásico"
    L["Slayer's Rise"] = "Alto del Asesino"
    L["Strand of the Ancients"] = "Playa de los Ancestros"
    L["Deephaul Ravine"] = "Barranco de Cargahonda"
    L["Ruins of Lordaeron"] = "Ruinas de Lordaeron"
    L["Dalaran Sewers"] = "Cloacas de Dalaran"
    L["Tol'Viron Arena"] = "Arena Tol'viron"
    L["The Tiger's Peak"] = "La Cima del Tigre"
    L["Black Rook Hold Arena"] = "Arena del Torreón Grajo Negro"
    L["Nagrand Arena"] = "Arena de Nagrand"
    L["Ashamane's Fall"] = "Caída de Crinceniza"
    L["Blade's Edge Arena"] = "Arena Filospada"
    L["Hook Point"] = "Puntagarfio"
    L["Mugambala"] = "Mugambala"
    L["The Robodrome"] = "Robotódromo"
    L["Empyrean Domain"] = "Dominio Empíreo"
    L["Maldraxxus Coliseum"] = "Coliseo de Maldraxxus"
    L["Enigma Crucible"] = "Crisol Enigma"
    L["Nokhudon Proving Grounds"] = "Terreno de pruebas Nokhudon"
    L["Cage of Carnage"] = "Jaula de la Matanza"
    L["All Arenas"] = "Todas las arenas"
return end

if LOCALE == "esMX" then
    -- Spanish (AL)
    L["Battleground Blitz"] = "Campo de batalla frenético"
    L["Solo Shuffle"] = "Aleatorio en solitario"
    L["Warsong Gulch"] = "Garganta Grito de Guerra"
    L["Twin Peaks"] = "Cumbres Gemelas"
    L["The Battle for Gilneas"] = "La Batalla por Gilneas"
    L["Eye of the Sorm"] = "Ojo de la Tormenta"
    L["Rated Eye of the Storm"] = "Ojo de la Tormenta puntuado"
    L["Temple of Kotmogu"] = "Templo de Kotmogu"
    L["Silvershard Mines"] = "Minas Lonjaplata"
    L["Seething Shore"] = "Costa Bullente"
    L["Arathi Basin"] = "Cuenca de Arathi"
    L["Deepwind Gorge"] = "Cañón del Céfiro"
    L["Deepwind Gorge (Legacy)"] = "Cañón del Céfiro (legado)"
    L["Alterac Valley"] = "Valle de Alterac"
    L["Isle of Conquest"] = "Isla de la Conquista"
    L["Battle for Wintergrasp"] = "Batalla por Conquista del Invierno"
    L["Ashran"] = "Ashran"
    L["Classic Ashran"] = "Ashran clásico"
    L["Slayer's Rise"] = "Alto del Asesino"
    L["Strand of the Ancients"] = "Playa de los Ancestros"
    L["Deephaul Ravine"] = "Barranco de Infrabundancia"
    L["Ruins of Lordaeron"] = "Ruinas de Lordaeron"
    L["Dalaran Sewers"] = "Cloacas de Dalaran"
    L["Tol'Viron Arena"] = "Arena Tol'viron"
    L["The Tiger's Peak"] = "La Cima del Tigre"
    L["Black Rook Hold Arena"] = "Arena del Fuerte Torre Oscura"
    L["Nagrand Arena"] = "Arena de Nagrand"
    L["Ashamane's Fall"] = "Caída de Ashamane"
    L["Blade's Edge Arena"] = "Arena Filospada"
    L["Hook Point"] = "Punta Garfio"
    L["Mugambala"] = "Mugambala"
    L["The Robodrome"] = "El Robódromo"
    L["Empyrean Domain"] = "Dominio Empíreo"
    L["Maldraxxus Coliseum"] = "Coliseo de Maldraxxus"
    L["Enigma Crucible"] = "Crisol Enigmático"
    L["Nokhudon Proving Grounds"] = "Terreno de Pruebas Nokhudon"
    L["Cage of Carnage"] = "Jaula de Carnicería"
    L["All Arenas"] = "Todas las arenas"
return end

if LOCALE == "frFR" then
    -- French
    L["Battleground Blitz"] = "Champ de bataille Blitz"
    L["Solo Shuffle"] = "Brassage solo"
    L["Warsong Gulch"] = "Goulet des Chanteguerres"
    L["Twin Peaks"] = "Pics-Jumeaux"
    L["The Battle for Gilneas"] = "La bataille de Gilnéas"
    L["Eye of the Sorm"] = "L’Œil du cyclone"
    L["Rated Eye of the Storm"] = "L’Œil du cyclone coté"
    L["Temple of Kotmogu"] = "Temple de Kotmogu"
    L["Silvershard Mines"] = "Mines d’Éclargent"
    L["Seething Shore"] = "Rivage Bouillonnant"
    L["Arathi Basin"] = "Bassin Arathi"
    L["Deepwind Gorge"] = "Gorge de Vent-Caverneux"
    L["Deepwind Gorge (Legacy)"] = "Gorge de Vent-Caverneux (héritage)"
    L["Alterac Valley"] = "Vallée d’Alterac"
    L["Isle of Conquest"] = "Île des Conquérants"
    L["Battle for Wintergrasp"] = "Bataille de Joug-d’Hiver"
    L["Ashran"] = "A’shran"
    L["Classic Ashran"] = "A’shran classique"
    L["Slayer's Rise"] = "Colline Meurtrière"
    L["Strand of the Ancients"] = "Rivage des Anciens"
    L["Deephaul Ravine"] = "Ravin d’Abondabîme"
    L["Ruins of Lordaeron"] = "Ruines de Lordaeron"
    L["Dalaran Sewers"] = "Égouts de Dalaran"
    L["Tol'Viron Arena"] = "Arène Tol’viron"
    L["The Tiger's Peak"] = "Le croc du Tigre"
    L["Black Rook Hold Arena"] = "Arène du bastion du Freux"
    L["Nagrand Arena"] = "Arène de Nagrand"
    L["Ashamane's Fall"] = "Chute d’Ashamane"
    L["Blade's Edge Arena"] = "Arène des Tranchantes"
    L["Hook Point"] = "Pointe du Crochet"
    L["Mugambala"] = "Mugambala"
    L["The Robodrome"] = "Le Robodrome"
    L["Empyrean Domain"] = "Domaine Empyréen"
    L["Maldraxxus Coliseum"] = "Maldraxxus Coliseum"
    L["Enigma Crucible"] = "Creuset des Énigmes"
    L["Nokhudon Proving Grounds"] = "Ordalie des Nokhuds"
    L["Cage of Carnage"] = "Cage du Carnage"
    L["All Arenas"] = "Toutes les arènes"
return end

if LOCALE == "itIT" then
    -- Italian
    L["Battleground Blitz"] = "Blitz nel Campo di Battaglia"
    L["Solo Shuffle"] = "Mischia Solitaria"
    L["Warsong Gulch"] = "Forra dei Cantaguerra"
    L["Twin Peaks"] = "Picchi Gemelli"
    L["The Battle for Gilneas"] = "Battaglia per Gilneas"
    L["Eye of the Sorm"] = "Occhio del Ciclone"
    L["Rated Eye of the Storm"] = "Occhio del Ciclone classificato"
    L["Temple of Kotmogu"] = "Tempio di Kotmogu"
    L["Silvershard Mines"] = "Miniere di Cupargento"
    L["Seething Shore"] = "Spiaggia Ribollente"
    L["Arathi Basin"] = "Bacino d'Arathi"
    L["Deepwind Gorge"] = "Scavi di Ventotetro"
    L["Deepwind Gorge (Legacy)"] = "Scavi di Ventotetro (Passati)"
    L["Alterac Valley"] = "Valle d'Alterac"
    L["Isle of Conquest"] = "Isola della Conquista"
    L["Battle for Wintergrasp"] = "Battaglia per Lungoinverno"
    L["Ashran"] = "Ashran"
    L["Classic Ashran"] = "Ashran classica"
    L["Slayer's Rise"] = "Altura del Carnefice"
    L["Strand of the Ancients"] = "Lido degli Antichi"
    L["Deephaul Ravine"] = "Gola Cavafonda"
    L["Ruins of Lordaeron"] = "Rovine di Lordaeron"
    L["Dalaran Sewers"] = "Fogne di Dalaran"
    L["Tol'Viron Arena"] = "Arena Tol'viron"
    L["The Tiger's Peak"] = "Picco della Tigre"
    L["Black Rook Hold Arena"] = "Arena del Forte Corvonero"
    L["Nagrand Arena"] = "Arena di Nagrand"
    L["Ashamane's Fall"] = "Caduta di Grigiomanto"
    L["Blade's Edge Arena"] = "Arena di Spinaguzza"
    L["Hook Point"] = "Presidio della Pesca"
    L["Mugambala"] = "Mugambala"
    L["The Robodrome"] = "Robodromo"
    L["Empyrean Domain"] = "Dominio Empireo"
    L["Maldraxxus Coliseum"] = "Maldraxxus Coliseum"
    L["Enigma Crucible"] = "Crogiolo dell'Enigma"
    L["Nokhudon Proving Grounds"] = "Arena d'Addestramento di Nokhudon"
    L["Cage of Carnage"] = "Gabbia della Carneficina"
    L["All Arenas"] = "Tutte le Arene"
return end

if LOCALE == "ptBR" then
    -- Brazilian Portuguese
    L["Battleground Blitz"] = "Ataque Relâmpago"
    L["Solo Shuffle"] = "Solo Mix"
    L["Warsong Gulch"] = "Ravina Brado Guerreiro"
    L["Twin Peaks"] = "Montes Gêmeos"
    L["The Battle for Gilneas"] = "A Batalha por Guilnéas"
    L["Eye of the Sorm"] = "Olho da Tormenta"
    L["Rated Eye of the Storm"] = "Olho da Tormenta ranqueado"
    L["Temple of Kotmogu"] = "Templo de Kotmogu"
    L["Silvershard Mines"] = "Minas Estilhaço Prateado"
    L["Seething Shore"] = "Praia Fervilhante"
    L["Arathi Basin"] = "Bacia Arathi"
    L["Deepwind Gorge"] = "Desfiladeiro do Vendaval"
    L["Deepwind Gorge (Legacy)"] = "Desfiladeiro do Vendaval (Legado)"
    L["Alterac Valley"] = "Vale Alterac"
    L["Isle of Conquest"] = "Ilha da Conquista"
    L["Battle for Wintergrasp"] = "Batalha por Invérnia"
    L["Ashran"] = "Ashran"
    L["Classic Ashran"] = "Ashran Clássica"
    L["Slayer's Rise"] = "Alto do Matador"
    L["Strand of the Ancients"] = "Baía dos Ancestrais"
    L["Deephaul Ravine"] = "Ravina Cargafunda"
    L["Ruins of Lordaeron"] = "Ruínas de Lordaeron"
    L["Dalaran Sewers"] = "Esgotos de Dalaran"
    L["Tol'Viron Arena"] = "Arena Tol'viron"
    L["The Tiger's Peak"] = "O Pico do Tigre"
    L["Black Rook Hold Arena"] = "Arena do Castelo Corvo Negro"
    L["Nagrand Arena"] = "Arena de Nagrand"
    L["Ashamane's Fall"] = "Queda de Ashamane"
    L["Blade's Edge Arena"] = "Arena da Lâmina Afiada"
    L["Hook Point"] = "Ponta do Gancho"
    L["Mugambala"] = "Mugambala"
    L["The Robodrome"] = "Robódromo"
    L["Empyrean Domain"] = "Domínio Empíreo"
    L["Maldraxxus Coliseum"] = "Coliseu de Maldraxxus"
    L["Enigma Crucible"] = "Crisol do Enigma"
    L["Nokhudon Proving Grounds"] = "Campo de Testes Nokhidon"
    L["Cage of Carnage"] = "Jaula da Carnificina"
    L["All Arenas"] = "Todas as Arenas"
return end

if LOCALE == "ruRU" then
    -- Russian
    L["Battleground Blitz"] = "Блиц по полям боя"
    L["Solo Shuffle"] = "Соло-суматоха"
    L["Warsong Gulch"] = "Ущелье Песни Войны"
    L["Twin Peaks"] = "Два Пика"
    L["The Battle for Gilneas"] = "Битва за Гилнеас"
    L["Eye of the Sorm"] = "Око Бури"
    L["Rated Eye of the Storm"] = "Око Бури (рейтинговое)"
    L["Temple of Kotmogu"] = "Храм Котмогу"
    L["Silvershard Mines"] = "Сверкающие копи"
    L["Seething Shore"] = "Бурлящий берег"
    L["Arathi Basin"] = "Низина Арати"
    L["Deepwind Gorge"] = "Каньон Суровых Ветров"
    L["Deepwind Gorge (Legacy)"] = "Каньон Суровых Ветров (наследие)"
    L["Alterac Valley"] = "Альтеракская долина"
    L["Isle of Conquest"] = "Остров Завоеваний"
    L["Battle for Wintergrasp"] = "Битва за озеро Ледяных Оков"
    L["Ashran"] = "Ашран"
    L["Classic Ashran"] = "Классический Ашран"
    L["Slayer's Rise"] = "Зубец убийцы"
    L["Strand of the Ancients"] = "Берег Древних"
    L["Deephaul Ravine"] = "Золотоносная падь"
    L["Ruins of Lordaeron"] = "Руины Лордерона"
    L["Dalaran Sewers"] = "Стоки Даларана"
    L["Tol'Viron Arena"] = "Арена Тол'вир"
    L["The Tiger's Peak"] = "Пик Тигра"
    L["Black Rook Hold Arena"] = "Арена крепости\r\nЧерной Ладьи"
    L["Nagrand Arena"] = "Арена Награнда"
    L["Ashamane's Fall"] = "Последнее пристанище Пеплошкурой"
    L["Blade's Edge Arena"] = "Арена Острогорья"
    L["Hook Point"] = "Большой Крюк"
    L["Mugambala"] = "Мугамбала"
    L["The Robodrome"] = "Рободром"
    L["Empyrean Domain"] = "Небесный домен"
    L["Maldraxxus Coliseum"] = "Колизей Малдраксуса"
    L["Enigma Crucible"] = "Горнило Тайн"
    L["Nokhudon Proving Grounds"] = "Арена испытаний Нокхудона"
    L["Cage of Carnage"] = "Клетка Крови"
    L["All Arenas"] = "Все арены"
return end

if LOCALE == "koKR" then
    -- Korean
    L["Battleground Blitz"] = "전장 대공세"
    L["Solo Shuffle"] = "1인 조합전"
    L["Warsong Gulch"] = "전쟁노래 협곡"
    L["Twin Peaks"] = "쌍둥이 봉우리"
    L["The Battle for Gilneas"] = "길니아스 전투지"
    L["Eye of the Sorm"] = "폭풍의 눈"
    L["Rated Eye of the Storm"] = "평점제 폭풍의 눈"
    L["Temple of Kotmogu"] = "코트모구의 사원"
    L["Silvershard Mines"] = "은빛수정 광산"
    L["Seething Shore"] = "들끓는 해안"
    L["Arathi Basin"] = "아라시 분지"
    L["Deepwind Gorge"] = "깊은바람 협곡"
    L["Deepwind Gorge (Legacy)"] = "깊은바람 협곡 (유산)"
    L["Alterac Valley"] = "알터랙 계곡"
    L["Isle of Conquest"] = "정복의 섬"
    L["Battle for Wintergrasp"] = "격전의 겨울손아귀"
    L["Ashran"] = "아쉬란"
    L["Classic Ashran"] = "클래식 아쉬란"
    L["Slayer's Rise"] = "학살자의 오름길"
    L["Strand of the Ancients"] = "고대의 해안"
    L["Deephaul Ravine"] = "깊은광혈 협곡"
    L["Ruins of Lordaeron"] = "로데론의 폐허"
    L["Dalaran Sewers"] = "달라란 하수도"
    L["Tol'Viron Arena"] = "톨비론 투기장"
    L["The Tiger's Peak"] = "범의 봉우리"
    L["Black Rook Hold Arena"] = "검은 떼까마귀 요새 투기장"
    L["Nagrand Arena"] = "나그란드 투기장"
    L["Ashamane's Fall"] = "아샤메인의 몰락지"
    L["Blade's Edge Arena"] = "칼날 산맥 투기장"
    L["Hook Point"] = "갈고리 시장"
    L["Mugambala"] = "무감발라"
    L["The Robodrome"] = "로봇 전투장"
    L["Empyrean Domain"] = "창공의 영지"
    L["Maldraxxus Coliseum"] = "말드락서스 대경기장"
    L["Enigma Crucible"] = "수수께끼 도가니"
    L["Nokhudon Proving Grounds"] = "노쿠드 수련의 장"
    L["Cage of Carnage"] = "살육의 우리"
    L["All Arenas"] = "모든 투기장"
return end

if LOCALE == "zhCN" then
    -- Simplified Chinese
    L["Battleground Blitz"] = "战场闪电战"
    L["Solo Shuffle"] = "单排轮斗"
    L["Warsong Gulch"] = "战歌峡谷"
    L["Twin Peaks"] = "双子峰"
    L["The Battle for Gilneas"] = "吉尔尼斯之战"
    L["Eye of the Sorm"] = "风暴之眼"
    L["Rated Eye of the Storm"] = "评级风暴之眼"
    L["Temple of Kotmogu"] = "寇魔古寺"
    L["Silvershard Mines"] = "碎银矿脉"
    L["Seething Shore"] = "涌泉海滩"
    L["Arathi Basin"] = "阿拉希盆地"
    L["Deepwind Gorge"] = "深风峡谷"
    L["Deepwind Gorge (Legacy)"] = "深风峡谷（经典）"
    L["Alterac Valley"] = "奥特兰克山谷"
    L["Isle of Conquest"] = "征服之岛"
    L["Battle for Wintergrasp"] = "冬拥湖之战"
    L["Ashran"] = "阿什兰"
    L["Classic Ashran"] = "经典阿什兰"
    L["Slayer's Rise"] = "屠戮者高地"
    L["Strand of the Ancients"] = "远古海滩"
    L["Deephaul Ravine"] = "御渊溪谷"
    L["Ruins of Lordaeron"] = "洛丹伦废墟"
    L["Dalaran Sewers"] = "达拉然下水道"
    L["Tol'Viron Arena"] = "托维尔隆竞技场"
    L["The Tiger's Peak"] = "虎踞峰"
    L["Black Rook Hold Arena"] = "黑鸦堡垒竞技场"
    L["Nagrand Arena"] = "纳格兰竞技场"
    L["Ashamane's Fall"] = "阿莎曼之墓"
    L["Blade's Edge Arena"] = "刀锋山竞技场"
    L["Hook Point"] = "锚角港"
    L["Mugambala"] = "穆贾巴拉"
    L["The Robodrome"] = "机械天穹"
    L["Empyrean Domain"] = "苍穹斗域"
    L["Maldraxxus Coliseum"] = "玛卓克萨斯角斗场"
    L["Enigma Crucible"] = "迷阵竞技场"
    L["Nokhudon Proving Grounds"] = "诺库顿试炼场"
    L["Cage of Carnage"] = "赤红围场"
    L["All Arenas"] = "所有竞技场"
return end

if LOCALE == "zhTW" then
    -- Traditional Chinese
    L["Battleground Blitz"] = "戰場閃擊戰"
    L["Solo Shuffle"] = "單人隨機"
    L["Warsong Gulch"] = "戰歌峽谷"
    L["Twin Peaks"] = "雙子峰"
    L["The Battle for Gilneas"] = "吉爾尼斯之戰"
    L["Eye of the Sorm"] = "暴風之眼"
    L["Rated Eye of the Storm"] = "暴風之眼積分戰場"
    L["Temple of Kotmogu"] = "科特魔古神廟"
    L["Silvershard Mines"] = "碎銀礦坑"
    L["Seething Shore"] = "騰湧海岸"
    L["Arathi Basin"] = "阿拉希盆地"
    L["Deepwind Gorge"] = "深風峽谷"
    L["Deepwind Gorge (Legacy)"] = "深風峽谷(懷舊)"
    L["Alterac Valley"] = "奧特蘭克山谷"
    L["Isle of Conquest"] = "征服之島"
    L["Battle for Wintergrasp"] = "冬握湖戰鬥"
    L["Ashran"] = "艾斯蘭"
    L["Classic Ashran"] = "經典艾斯蘭"
    L["Slayer's Rise"] = "殺戮者高地"
    L["Strand of the Ancients"] = "遠祖灘頭"
    L["Deephaul Ravine"] = "礦運深谷"
    L["Ruins of Lordaeron"] = "羅德隆廢墟"
    L["Dalaran Sewers"] = "達拉然下水道"
    L["Tol'Viron Arena"] = "托維恩競技場"
    L["The Tiger's Peak"] = "猛虎峰"
    L["Black Rook Hold Arena"] = "玄鴉堡競技場"
    L["Nagrand Arena"] = "納葛蘭競技場"
    L["Ashamane's Fall"] = "亞夏曼之殞"
    L["Blade's Edge Arena"] = "劍刃競技場"
    L["Hook Point"] = "勾角地"
    L["Mugambala"] = "穆干巴拉"
    L["The Robodrome"] = "超爆機械鬥場"
    L["Empyrean Domain"] = "蒼穹領域"
    L["Maldraxxus Coliseum"] = "瑪卓薩斯大競技場"
    L["Enigma Crucible"] = "神秘之爐"
    L["Nokhudon Proving Grounds"] = "諾庫敦試煉場"
    L["Cage of Carnage"] = "兇殘牢籠"
    L["All Arenas"] = "所有競技場"
return end
