-- Localization.lua: WarGames+ localization system
-- Loaded FIRST in the .toc before all other files.
-- Usage: local L = WargamesPlus.L  (in core.lua, tracker.lua, comm.lua)

-- Bootstrap the global namespace early so L is available to all files
if not _G["WargamesPlus"] then _G["WargamesPlus"] = {} end
local WG = _G["WargamesPlus"]

-- Keybinding globals (WoW reads these directly from _G)
BINDING_HEADER_WARGAMESPLUS = "Wargames+"
BINDING_NAME_WARGAMESPLUS_TOGGLE = "Toggle Window"
BINDING_NAME_WARGAMESPLUS_DOCK = "Toggle Dock Mode"

local L = setmetatable({}, {
    __index = function(t, k)
        -- Fallback: return the key itself if no translation exists
        local v = tostring(k)
        rawset(t, k, v)
        return v
    end,
})

WG.L = L

-- ============================================================
-- English (enUS) -- Base locale: all keys defined here
-- ============================================================

-- Addon identity
L["ADDON_TITLE"]                = "WARGAMES+"
L["ADDON_TITLE_TOOLTIP"]        = "WarGames+"
L["ADDON_LOADED"]               = "WarGames+ Loaded."
L["ADDON_AUTHOR"]               = "By Waxilliam"
L["CHAT_PREFIX"]                = "[WG+]"

-- Main UI labels
L["FRIENDS"]                    = "FRIENDS"
L["THEME_LABEL"]                = "Theme:"
L["FONT_LABEL"]                 = "Font:"
L["FONT_RELOAD_HINT"]           = "Type /reload to apply the new font everywhere."
L["CUSTOM_THEME"]               = "CUSTOM THEME"
L["BASE_LABEL"]                 = "Base:"
L["TYPE_LABEL"]                 = "Type:"
L["MODE_HEADER"]                = "GAME MODE"
L["MAP_HEADER"]                 = "MAP"
L["TARGET_HEADER"]              = "TARGET"
L["MAP_MANAGE_HINT"]            = "Drag to reorder \194\183 right-click for options"
L["MAP_MOVE_TOP"]               = "Move to Top"
L["MAP_MOVE_UP"]                = "Move Up"
L["MAP_MOVE_DOWN"]              = "Move Down"

-- Buttons
L["REFRESH"]                    = "Refresh"
L["TARGET"]                     = "Target"
L["COLLAPSE"]                   = "Collapse"
L["EXPAND"]                     = "Expand"
L["STATS"]                      = "History"
L["SIDEBAR_ADVANCED"]           = "Advanced"
L["SIDEBAR_SLAUGHTER"]          = "Slaughterhouse"
L["SIDEBAR_SETTINGS"]           = "Settings"
L["HELP"]                       = "Help"
L["SEARCH_FRIENDS"]             = "Search friends..."
L["FILTER_ALL"]                 = "All"
L["FILTER_FAVORITES"]           = "Favorites"
L["FILTER_ONLINE"]              = "Online"
L["SPECTATE"]                   = "Spectate"
L["SPECTATE_MODE"]              = "Spectate Mode"
L["CHALLENGE_MODE"]             = "Challenge"
L["RESET"]                      = "Reset"

-- Challenge / Spectator
L["SEND_CHALLENGE"]             = "Send Challenge"
L["SPECTATE_MATCH"]             = "Spectate Match"
L["LEADER_1"]                   = "Leader 1:"
L["LEADER_2"]                   = "Leader 2:"
L["TOURNAMENT_RULES"]           = "Tournament Rules"
L["RECENT_OPPONENTS"]           = "Recent Opponents"

-- Tabs
L["TAB_ARENAS"]                 = "Arenas"
L["TAB_BATTLEGROUNDS"]          = "Battlegrounds"

-- Radio button labels (game mode sub-types)
L["MODE_2V2"]                   = "2v2"
L["MODE_3V3"]                   = "3v3"
L["MODE_5V5"]                   = "5v5"
L["MODE_SHUFFLE"]               = "Shuffle"
L["MODE_NORMAL"]                = "Normal"
L["MODE_BLITZ"]                 = "Blitz"

-- Map list
L["RANDOM_MAP"]                 = "Random Map"

-- Context menu
L["WHISPER_CHARACTER"]           = "Whisper Character"
L["INVITE_CHARACTER"]            = "Invite Character"
L["FAVORITE"]                    = "Favorite"
L["UNFAVORITE"]                  = "Unfavorite"
L["VIEW_PROFILE"]                = "View Profile"
L["SEND_CHALLENGE_MENU"]         = "Send Challenge"
L["INCLUDE_IN_RANDOM"]           = "Include in Random"
L["EXCLUDE_FROM_RANDOM"]         = "Exclude from Random"

-- Chat messages
L["MSG_CHALLENGE_SENT"]          = "Challenge sent to %s on %s"
L["MSG_RANDOM_SELECTED"]         = "Randomly selected: %s"
L["MSG_ALL_MAPS_EXCLUDED"]       = "Warning: All maps excluded, using full pool."
L["MSG_BOTH_LEADERS_REQUIRED"]   = "Both party leaders must be specified."
L["MSG_CANNOT_RESOLVE_BNET"]     = "Could not resolve BNet ID for: %s"
L["MSG_SPECTATING"]              = "Spectating: %s vs %s on %s"
L["MSG_HISTORY_CLEARED"]         = "Match history cleared."
L["MSG_MATCH_RESULT"]            = "Match result: %s vs %s on %s"

-- Tracker panel
L["MATCH_HISTORY"]               = "MATCH HISTORY"
L["CLEAR_HISTORY"]               = "Clear History"
L["CONFIRM_CLEAR"]               = "Confirm?"
L["NO_MATCH_DATA"]               = "No match data yet"
L["NO_MATCHES_RECORDED"]         = "No matches recorded"
L["NO_MATCHES_VS_OPPONENT"]      = "No matches vs this opponent"
L["WIN_RATE"]                    = "win rate"
L["STREAK"]                     = "Streak:"
L["BEST"]                       = "Best:"
L["CURRENT_STREAK"]             = "Current streak:"
L["RECORDS_COUNT"]               = "%d / %d records"

-- Tracker tab names
L["TAB_OPPONENTS"]               = "Opponents"
L["TAB_MAPS"]                    = "Maps"
L["TAB_LOG"]                     = "Log"
L["TAB_SESSION"]                 = "Session"

-- Session recap
L["SESSION_TITLE"]               = "Session Recap"
L["SESSION_START"]               = "Start Session"
L["SESSION_END"]                 = "End Session"
L["SESSION_COPY"]                = "Copy for Discord"
L["SESSION_NO_MATCHES"]          = "No matches in this session yet."
L["SESSION_AUTO_HINT"]           = "Auto: matches within 2h of each other"
L["SESSION_MANUAL_HINT"]         = "Manual session running"
L["SESSION_RECORD"]              = "Record"
L["SESSION_LENGTH"]              = "Length"
L["SESSION_BY_MODE"]             = "By mode"
L["SESSION_BY_MAP"]              = "By map"
L["SESSION_TOP_OPP"]             = "Top opponent"

-- Match notes / context menu
L["NOTE_ADD"]                    = "Add Note"
L["NOTE_EDIT"]                   = "Edit Note"
L["NOTE_TITLE"]                  = "Match Note"
L["NOTE_HEADER"]                 = "NOTE"
L["MATCH_DELETE"]                = "Delete Match"
L["VIEW_VETO"]                   = "View Veto"
L["VETO_RECAP_HEADER"]           = "MAP VETO"

-- Detail panel headers
L["YOUR_PERFORMANCE"]            = "YOUR PERFORMANCE"
L["WINNERS"]                     = "WINNERS"
L["LOSERS"]                      = "LOSERS"
L["PLAYERS"]                     = "PLAYERS"

-- Result labels
L["WIN"]                         = "WIN"
L["LOSS"]                        = "LOSS"
L["DRAW"]                        = "DRAW"
L["WIN_SHORT"]                   = "W"
L["LOSS_SHORT"]                  = "L"
L["DRAW_SHORT"]                  = "D"

-- Stat abbreviations (used in detail panel)
L["STAT_DMG"]                    = "dmg"
L["STAT_HEAL"]                   = "heal"
L["STAT_KB"]                     = "KB"
L["STAT_DEATHS"]                 = "D"
L["STAT_ROUNDS_WON"]             = "rounds won"
L["STAT_ROUNDS_SHORT"]           = "R"

-- Time ago suffixes
L["TIME_SECONDS_AGO"]            = "%ds ago"
L["TIME_MINUTES_AGO"]            = "%dm ago"
L["TIME_HOURS_AGO"]              = "%dh ago"
L["TIME_DAYS_AGO"]               = "%dd ago"

-- Map / arena display names (used in ARENA_LIST, BG_LIST, BLITZ_LIST)
-- NOTE: These are display-only. The internal MAP_DATA keys always use English.
L["Nagrand Arena"]               = "Nagrand Arena"
L["Blade's Edge Arena"]          = "Blade's Edge Arena"
L["Ruins of Lordaeron"]          = "Ruins of Lordaeron"
L["Dalaran Arena"]               = "Dalaran Arena"
L["Ring of Valor"]               = "Ring of Valor"
L["Tol'viron Arena"]             = "Tol'viron Arena"
L["Tiger's Peak"]                = "Tiger's Peak"
L["Ashamane's Fall"]             = "Ashamane's Fall"
L["Black Rook Hold Arena"]       = "Black Rook Hold Arena"
L["Hook Point"]                  = "Hook Point"
L["Mugambala"]                   = "Mugambala"
L["Maldraxxus Coliseum"]         = "Maldraxxus Coliseum"
L["Nokhudon Proving Grounds"]    = "Nokhudon Proving Grounds"
L["Warsong Gulch"]               = "Warsong Gulch"
L["Twin Peaks"]                  = "Twin Peaks"
L["Arathi Basin"]                = "Arathi Basin"
L["The Battle for Gilneas"]      = "The Battle for Gilneas"
L["Battle for Gilneas"]          = "Battle for Gilneas"
L["Eye of the Storm"]            = "Eye of the Storm"
L["Temple of Kotmogu"]           = "Temple of Kotmogu"
L["Silvershard Mines"]           = "Silvershard Mines"
L["Seething Shore"]              = "Seething Shore"
L["Deephaul Ravine"]             = "Deephaul Ravine"
L["Deepwind Gorge"]              = "Deepwind Gorge"
L["The Robodrome"]               = "The Robodrome"
L["Empyrean Domain"]             = "Empyrean Domain"
L["Enigma Crucible"]             = "Enigma Crucible"
L["Cage of Carnage"]             = "Cage of Carnage"

-- Map status labels
L["MAP_EXCLUDED_SUFFIX"]         = "(excluded)"

-- Custom theme editor group labels
L["THEME_ACCENT"]                = "Accent"
L["THEME_BACKGROUND"]            = "Background"
L["THEME_BORDER"]                = "Border"
L["THEME_BUTTON"]                = "Button"
L["THEME_TEXT"]                   = "Text"
L["THEME_CLOSE_HOVER"]           = "Close/Hover"
L["THEME_WIN_COLOR"]             = "Win Color"
L["THEME_LOSS_COLOR"]            = "Loss Color"

-- Mode labels for match records (displayed in log)
L["MODE_LABEL_2V2"]              = "2v2"
L["MODE_LABEL_3V3"]              = "3v3"
L["MODE_LABEL_5V5"]              = "5v5"
L["MODE_LABEL_SOLO_SHUFFLE"]     = "Solo Shuffle"
L["MODE_LABEL_BG"]               = "BG"
L["MODE_LABEL_BLITZ"]            = "Blitz"

-- Compact mode
L["COMPACT"]                     = "Compact"

-- Map win rate (shown on map buttons)
L["MAP_STATS_PLAYED"]            = "(%d played)"

-- Minimap tooltip
L["TODAY_RECORD"]                = "Today: %s"

-- Friend tooltip
L["RECORD_LABEL"]                = "Record:"
L["WIN_RATE_LABEL"]              = "Win Rate:"

-- Ban system
L["BAN_MIN_MAPS"]                = "Need at least 3 maps in pool for ban mode."
L["BAN_MODE"]                    = "Ban Mode"
L["BAN_MODE_SHORT"]              = "Ban"
L["BAN_SUBMIT"]                  = "Submit Bans"
L["BAN_WAITING"]                 = "Waiting for opponent..."
L["BAN_COUNT"]                   = "Bans: %d / %d"
L["BAN_RESULT"]                  = "Map selected: %s"
L["BAN_CANCELLED"]               = "Ban phase cancelled."
L["MSG_OPPONENT_NO_ADDON"]       = "Opponent does not have WG+ installed."
L["ADDON_DETECTED"]              = "[WG+]"
L["BANS_PER_PLAYER"]             = "Bans per player:"
L["BAN_BANNED_SUFFIX"]           = "[BANNED]"
L["BAN_NO_OPPONENT"]             = "Enter an opponent name first."

-- Veto system
L["VETO_MODE"]                   = "Veto Mode"
L["VETO_MODE_SHORT"]             = "Veto"
L["VETO_TITLE"]                  = "MAP VETO"
L["VETO_INVITE_SENT"]            = "Veto invite sent to %s (%s)"
L["VETO_INVITE_RECEIVED"]        = "%s wants to start a %s map veto!"
L["VETO_ACCEPT"]                 = "Accept"
L["VETO_DECLINE"]                = "Decline"
L["VETO_YOUR_TURN_BAN"]          = "YOUR TURN — BAN a map"
L["VETO_YOUR_TURN_PICK"]         = "YOUR TURN — PICK a map"
L["VETO_OPPONENT_TURN"]          = "Waiting for %s..."
L["VETO_BANNED"]                 = "%s banned %s"
L["VETO_PICKED"]                 = "%s picked %s"
L["VETO_COMPLETE"]               = "Veto complete!"
L["VETO_FINAL_MAP"]              = "Final map: %s"
L["VETO_READY"]                  = "Ready"
L["VETO_CANCELLED"]              = "Veto cancelled."
L["VETO_TIMEOUT"]                = "Veto timed out."
L["VETO_NO_ADDON"]               = "Opponent doesn't have WG+ installed."
L["VETO_FORMAT_BO1"]             = "Best of 1"
L["VETO_FORMAT_BO3"]             = "Best of 3"
L["VETO_FORMAT_BO5"]             = "Best of 5"
L["VETO_SELECT_FORMAT"]          = "Select Veto Format"
L["VETO_SERIES_MAP"]             = "Map %d: %s"
L["VETO_SERIES_MAP_SHORT"]       = "Map"
L["VETO_SERIES_DECIDER"]         = "Decider"
L["VETO_SERIES_LABEL"]           = "SERIES"
L["VETO_BEST_OF"]                = "BEST OF %s"
L["VETO_WAITING_OPPONENT"]       = "Waiting on opponent\226\128\166"
L["VETO_HISTORY"]                = "Veto History"
L["VETO_MIN_MAPS"]               = "Need at least %d maps for %s veto."
L["VETO_TURN_PROGRESS"]          = "Turn %d / %d"
L["VETO_START"]                  = "Start Veto"
L["VETO_NO_OPPONENT"]            = "Enter an opponent name first."

-- Ready check
L["RC_TITLE"]                    = "READY CHECK"
L["RC_SHORT"]                    = "RC"
L["RC_START"]                    = "Ready Check"
L["RC_MY_TEAM"]                  = "MY TEAM"
L["RC_OPPONENT"]                 = "OPPONENT"
L["RC_OPP_READY"]                = "Opponent team ready"
L["RC_OPP_WAITING"]              = "Waiting on opponent\226\128\166"
L["RC_WAITING_INIT"]             = "Waiting for %s to send the challenge\226\128\166"
L["RC_SEND"]                     = "Send Challenge"
L["RC_READY"]                    = "Ready"
L["RC_ASSUMED"]                  = "no addon \226\128\148 assumed ready"
L["RC_NO_OPPONENT"]              = "Enter an opponent name first."
L["RC_DETECTING"]                = "Checking whether %s has Wargames+\226\128\166"
L["RC_NO_ADDON"]                 = "That player needs Wargames+ for a ready check."
L["RC_CANCELLED"]                = "Ready check cancelled."
L["RC_TIMEOUT"]                  = "Ready check timed out."
L["RC_INVITE_RECEIVED"]          = "%s started a ready check."

-- Slaughterhouse (toon-declaration draft)
L["SLAUGHTER_TITLE"]             = "SLAUGHTERHOUSE"
L["SLAUGHTER_SETUP_HINT"]        = "Randomize a draft order and declare your toon, one at a time."
L["SLAUGHTER_FORMAT_LABEL"]      = "Format:"
L["SLAUGHTER_MY_GROUP_LABEL"]    = "My Group:"
L["SLAUGHTER_CONTACT_LABEL"]     = "Opponent Contact:"
L["SLAUGHTER_START"]             = "Start Slaughterhouse"
L["SLAUGHTER_DECLARE_BTN"]       = "Declare"
L["SLAUGHTER_POST_CHAT"]         = "Post to Party Chat"
L["SLAUGHTER_INVITE_SENT"]       = "Slaughterhouse invite sent to %s."
L["SLAUGHTER_INVITE_RECEIVED"]   = "%s wants to start a Slaughterhouse draft!"
L["SLAUGHTER_ACCEPTED"]          = "%s accepted the Slaughterhouse invite."
L["SLAUGHTER_DECLINED"]          = "%s declined: %s"
L["SLAUGHTER_CANCELLED"]         = "Slaughterhouse cancelled."
L["SLAUGHTER_TIMEOUT"]           = "Slaughterhouse invite timed out."
L["SLAUGHTER_NO_ADDON"]          = "Opponent doesn't have WG+ installed."
L["SLAUGHTER_GROUP_SIZE_MISMATCH"] = "Need exactly %d players in your group (found %d)."
L["SLAUGHTER_ORDER_RECEIVED"]    = "Slaughterhouse draft order received!"
L["SLAUGHTER_WAITING_ACCEPT"]    = "Waiting for %s to accept..."
L["SLAUGHTER_WAITING_ORDER"]     = "Waiting for the draft order..."
L["SLAUGHTER_YOUR_TURN"]         = "YOUR TURN — DECLARE YOUR TOON"
L["SLAUGHTER_WAITING_ON"]        = "Waiting for %s..."
L["SLAUGHTER_COMPLETE"]          = "Slaughterhouse complete!"
L["SLAUGHTER_TURN_PROGRESS"]     = "Turn %d / %d"
L["SLAUGHTER_DECLARED"]          = "%s declared %s"

-- LFG system
L["LFG"]                         = "LFG"
L["LFG_TITLE"]                   = "LOOKING FOR WARGAMES"
L["LFG_POST"]                    = "Post"
L["LFG_UNPOST"]                  = "Unpost"
L["LFG_BRACKET"]                 = "Bracket:"
L["LFG_NOTE"]                    = "Note:"
L["LFG_NOTE_PLACEHOLDER"]        = "optional"
L["LFG_NO_POSTS"]                = "No one is looking right now."
L["LFG_POSTED"]                  = "Posted LFG: %s"
L["LFG_UNPOSTED"]                = "LFG post cleared."
L["LFG_RATE_LIMITED"]            = "Please wait before posting again."
L["LFG_IN_INSTANCE"]             = "Cannot post LFG while inside an arena or battleground."
L["LFG_RIGHT_CLICK_CHALLENGE"]   = "Challenge"
L["LFG_RIGHT_CLICK_WHISPER"]     = "Whisper"
L["LFG_RIGHT_CLICK_ADD_FRIEND"]  = "Add Friend"
L["LFG_RIGHT_CLICK_HIDE"]        = "Hide Poster"
L["LFG_JUST_NOW"]                = "just now"
L["LFG_MIN_AGO"]                 = "%dm ago"
L["LFG_COL_NAME"]                = "Name"
L["LFG_COL_BRACKET"]             = "Bracket"
L["LFG_COL_NOTE"]                = "Note"
L["LFG_COL_AGE"]                 = "Age"
L["LFG_COL_H2H"]                 = "H2H"
L["LFG_YOU"]                     = "YOU"
L["LFG_EXPIRES_IN"]              = "Your post expires in %dm"
L["LFG_REFRESH"]                 = "Refresh"
L["LFG_SECTION_POST"]            = "Post a Listing"
L["LFG_SECTION_FILTERS"]         = "Filters"
L["LFG_FILTER"]                  = "Filter:"
L["LFG_SEARCH"]                  = "search notes"
L["LFG_FACTION_ALL"]             = "All"
L["LFG_FACTION_HORDE"]           = "H"
L["LFG_FACTION_ALLIANCE"]        = "A"
L["LFG_BRACKET_ANY"]             = "Any"
L["LFG_MODE_LIVE"]               = "Live"
L["LFG_MODE_HISTORY"]            = "History"
L["LFG_RIGHT_CLICK_VETO"]        = "Start Veto"
L["LFG_HEAD_TO_HEAD"]            = "%d-%d"
L["LFG_ENABLED"]                 = "Enable LFG (auto-join channel)"
L["LFG_MANAGE_IGNORED"]          = "Manage Hidden Posters"
L["LFG_IGNORED_TITLE"]           = "HIDDEN POSTERS"
L["LFG_IGNORED_EMPTY"]           = "No posters hidden."
L["LFG_IGNORED_UNHIDE"]          = "Unhide"
L["LFG_SETTINGS_HEADER"]         = "LFG"
L["LFG_COMMUNITY_HINT"]          = "Join the WargamesPlus community for cross-realm LFG:"
L["LFG_COMMUNITY_INVITE_URL"]    = "https://www.worldofwarcraft.com/invite/ApGyKDyujND"
L["LFG_COMMUNITY_COPY"]          = "Copy Link"
L["LFG_COMMUNITY_COPY_PROMPT"]   = "Press Ctrl+C to copy the invite link, then paste it into your browser:"
L["LFG_COMMUNITY_STREAM_MISSING"] = "WargamesPlus community joined but #lfg-traffic stream missing — ask author for an updated invite."
L["LFG_COMMUNITY_OPEN_PANEL"]    = "Open Communities Panel"
L["LFG_REACH_LABEL"]             = "Reach:"
L["LFG_REACH_REALM"]             = "realm"
L["LFG_REACH_GUILD"]             = "guild"
L["LFG_REACH_COMMUNITY"]         = "WargamesPlus community"
L["LFG_REACH_TOOLTIP_REALM"]     = "Players on your realm with WG+ installed"
L["LFG_REACH_TOOLTIP_GUILD"]     = "Guildmates on any realm with WG+ installed"
L["LFG_REACH_TOOLTIP_COMMUNITY"] = "Cross-realm WG+ users who joined the WargamesPlus community"
L["LFG_DISABLED"]                = "LFG is disabled in settings."

-- Help panel
L["HELP_TITLE"]                  = "HOW TO USE WARGAMES+"
L["HELP_SECTION_BASICS"]         = "BASICS"
L["HELP_OPPONENT_FIELD"]         = "Opponent Field — Type a character name or BattleTag to challenge."
L["HELP_TARGET_BTN"]             = "Target — Auto-fills with your current target's name."
L["HELP_RECENT_DROPDOWN"]        = "Recent Opponents — Dropdown of your last 10 opponents."
L["HELP_SECTION_MODES"]          = "GAME MODES"
L["HELP_GAME_MODES"]             = "Use the radio buttons to pick: 2v2, 3v3, 5v5, Shuffle, Normal BG, or Blitz. The map list updates to match."
L["HELP_MAP_SELECT"]             = "Click a map to select it. 'Random Map' picks one at random (excluding any you've excluded)."
L["HELP_SECTION_FEATURES"]       = "FEATURES"
L["HELP_BAN_MAPS"]               = "Ban Maps — Both players secretly ban maps, then a random map is chosen from the remaining pool. Requires opponent to have WG+."
L["HELP_VETO"]                   = "Veto — CS2-style alternating map ban/pick. Choose Bo1, Bo3, or Bo5. Players take turns banning maps until a final map remains. Requires opponent to have WG+."
L["HELP_SPECTATE"]               = "Spectate — Watch two other players fight."
L["HELP_SPECTATE_1"]             = "  1. Click the Spectate button to enable spectator mode."
L["HELP_SPECTATE_2"]             = "  2. Two name fields appear: enter each team's party leader."
L["HELP_SPECTATE_3"]             = "  3. Select a map and game mode, then click Send Challenge."
L["HELP_SPECTATE_4"]             = "  4. Both leaders must accept the wargame invite to start."
L["HELP_TOURNAMENT"]             = "Tournament Rules — Checkbox to enable tournament rules for the wargame."
L["HELP_SECTION_EXTRAS"]         = "EXTRAS"
L["HELP_STATS"]                  = "Stats — Opens match history tracker with win/loss records, opponent profiles, and map stats."
L["HELP_THEMES"]                 = "Themes — Pick Midnight, Horde, Alliance, or create a Custom theme with the color editor."
L["HELP_RIGHT_CLICK"]            = "Right-Click — Right-click friends for quick actions (whisper, invite, profile, challenge, veto). Right-click maps to favorite or exclude."
L["HELP_SECTION_LFG"]            = "LFG"
L["HELP_LFG"]                    = "LFG — Click the accent-colored LFG button to find (or advertise to) other players looking for wargames."
L["HELP_LFG_POST"]               = "  1. Pick a bracket, type an optional note, click Post. Your post refreshes every 2 minutes and expires after 10."
L["HELP_LFG_BROWSE"]             = "  2. Browse the live list. Use the filter bar (bracket / faction / note search) to narrow it down."
L["HELP_LFG_INTERACT"]           = "  3. Left-click a row to fire a challenge instantly. Right-click for Challenge, Start Veto, Whisper, Add Friend, or Hide Poster."
L["HELP_LFG_BADGE"]              = "  4. The [WG+] badge marks posters who have the addon — veto and challenge handshakes are guaranteed to work."
L["HELP_LFG_H2H"]                = "  5. The W-L column shows your head-to-head record against each poster (green if winning, red if losing)."
L["HELP_LFG_HISTORY"]            = "  6. Toggle Live/History at the top to browse recent advertisers even after they've dropped off."
L["HELP_LFG_REACH"]              = "LFG Reach — Posts go out to guildmates (any realm) and WargamesPlus community members (any realm, any faction). Join the community via the invite link in README for cross-realm reach."
L["HELP_DRAG_MAPS"]              = "Manage Maps — Drag map tiles to reorder them (your order is saved). Right-click a tile to favorite it, exclude it from Random, or move it."

-- Dock mode
L["DOCK_TITLE"]                  = "WG+ DOCK"
L["DOCK_MODE"]                   = "Dock"
L["DOCK_NO_FRIEND"]              = "No friend selected"
L["DOCK_SELECT_FRIEND"]          = "Select a friend in the Friends List"
L["DOCK_UPDATE"]                 = "Update"
L["DOCK_NOT_ONLINE"]             = "Friend is not online or not in WoW"
L["DOCK_SPECTATOR_TOGGLE"]      = "Spectate"
L["DOCK_LEADER_1"]               = "Leader 1:"
L["DOCK_LEADER_2"]               = "Leader 2:"
L["DOCK_FROM_SELECTION"]         = "From Selection"

-- ============================================================
-- Non-English locales
-- ============================================================
local LOCALE = GetLocale()

if LOCALE == "deDE" then
    -- German
    BINDING_NAME_WARGAMESPLUS_TOGGLE = "Fenster umschalten"
    BINDING_NAME_WARGAMESPLUS_DOCK = "Dock-Modus umschalten"
    L["ADDON_LOADED"]               = "WarGames+ geladen."
    L["FRIENDS"]                    = "FREUNDE"
    L["THEME_LABEL"]                = "Thema:"
    L["CUSTOM_THEME"]               = "EIGENES THEMA"
    L["BASE_LABEL"]                 = "Basis:"
    L["TYPE_LABEL"]                 = "Typ:"
    L["REFRESH"]                    = "Aktualisieren"
    L["TARGET"]                     = "Ziel"
    L["COLLAPSE"]                   = "Einklappen"
    L["EXPAND"]                     = "Ausklappen"
    L["STATS"]                      = "Statistik"
    L["SPECTATE"]                   = "Zuschauen"
    L["CHALLENGE_MODE"]             = "Herausfordern"
    L["RESET"]                      = "Zurücksetzen"
    L["SEND_CHALLENGE"]             = "Herausforderung senden"
    L["SPECTATE_MATCH"]             = "Match beobachten"
    L["LEADER_1"]                   = "Anführer 1:"
    L["LEADER_2"]                   = "Anführer 2:"
    L["TOURNAMENT_RULES"]           = "Turnierregeln"
    L["RECENT_OPPONENTS"]           = "Letzte Gegner"
    L["TAB_ARENAS"]                 = "Arenen"
    L["TAB_BATTLEGROUNDS"]          = "Schlachtfelder"
    L["MODE_SHUFFLE"]               = "Gemischt"
    L["MODE_NORMAL"]                = "Normal"
    L["RANDOM_MAP"]                 = "Zufällige Karte"
    L["WHISPER_CHARACTER"]          = "Flüstern"
    L["INVITE_CHARACTER"]           = "Einladen"
    L["FAVORITE"]                   = "Favorit"
    L["UNFAVORITE"]                 = "Entfernen"
    L["VIEW_PROFILE"]               = "Profil ansehen"
    L["SEND_CHALLENGE_MENU"]        = "Herausforderung senden"
    L["INCLUDE_IN_RANDOM"]          = "In Zufall einschließen"
    L["EXCLUDE_FROM_RANDOM"]        = "Aus Zufall ausschließen"
    L["MSG_CHALLENGE_SENT"]         = "Herausforderung gesendet an %s auf %s"
    L["MSG_RANDOM_SELECTED"]        = "Zufällig ausgewählt: %s"
    L["MSG_ALL_MAPS_EXCLUDED"]      = "Warnung: Alle Karten ausgeschlossen, verwende vollen Pool."
    L["MSG_BOTH_LEADERS_REQUIRED"]  = "Beide Gruppenanführer müssen angegeben werden."
    L["MSG_CANNOT_RESOLVE_BNET"]    = "Konnte BNet-ID nicht auflösen für: %s"
    L["MSG_SPECTATING"]             = "Beobachte: %s gegen %s auf %s"
    L["MSG_HISTORY_CLEARED"]        = "Spielverlauf gelöscht."
    L["MSG_MATCH_RESULT"]           = "Ergebnis: %s gegen %s auf %s"
    L["MATCH_HISTORY"]              = "SPIELVERLAUF"
    L["CLEAR_HISTORY"]              = "Verlauf löschen"
    L["CONFIRM_CLEAR"]              = "Bestätigen?"
    L["NO_MATCH_DATA"]              = "Noch keine Spieldaten"
    L["NO_MATCHES_RECORDED"]        = "Keine Spiele aufgezeichnet"
    L["NO_MATCHES_VS_OPPONENT"]     = "Keine Spiele gegen diesen Gegner"
    L["WIN_RATE"]                   = "Siegesrate"
    L["STREAK"]                     = "Serie:"
    L["BEST"]                       = "Beste:"
    L["CURRENT_STREAK"]             = "Aktuelle Serie:"
    L["RECORDS_COUNT"]              = "%d / %d Einträge"
    L["TAB_OPPONENTS"]              = "Gegner"
    L["TAB_MAPS"]                   = "Karten"
    L["TAB_LOG"]                    = "Verlauf"
    L["YOUR_PERFORMANCE"]           = "DEINE LEISTUNG"
    L["WINNERS"]                    = "GEWINNER"
    L["LOSERS"]                     = "VERLIERER"
    L["PLAYERS"]                    = "SPIELER"
    L["WIN"]                        = "SIEG"
    L["LOSS"]                       = "NIEDERLAGE"
    L["DRAW"]                       = "UNENTSCHIEDEN"
    L["WIN_SHORT"]                  = "S"
    L["LOSS_SHORT"]                 = "N"
    L["DRAW_SHORT"]                 = "U"
    L["STAT_DMG"]                   = "Schaden"
    L["STAT_HEAL"]                  = "Heilung"
    L["TIME_SECONDS_AGO"]           = "vor %ds"
    L["TIME_MINUTES_AGO"]           = "vor %dm"
    L["TIME_HOURS_AGO"]             = "vor %dh"
    L["TIME_DAYS_AGO"]              = "vor %dd"
    L["MAP_EXCLUDED_SUFFIX"]        = "(ausgeschlossen)"
    L["THEME_ACCENT"]               = "Akzent"
    L["THEME_BACKGROUND"]           = "Hintergrund"
    L["THEME_BORDER"]               = "Rahmen"
    L["THEME_BUTTON"]               = "Schaltfläche"
    L["THEME_TEXT"]                  = "Text"
    L["THEME_CLOSE_HOVER"]          = "Schließen/Hover"
    L["THEME_WIN_COLOR"]            = "Siegfarbe"
    L["THEME_LOSS_COLOR"]           = "Niederlagenfarbe"
    L["MODE_LABEL_SOLO_SHUFFLE"]    = "Gemischtes Einzel"
    L["COMPACT"]                    = "Kompakt"
    L["MAP_STATS_PLAYED"]           = "(%d gespielt)"
    L["BAN_MODE"]                   = "Karten bannen"
    L["BAN_SUBMIT"]                 = "Bans senden"
    L["BAN_WAITING"]                = "Warte auf Gegner..."
    L["BAN_COUNT"]                  = "Bans: %d / %d"
    L["BAN_RESULT"]                 = "Karte ausgewählt: %s"
    L["BAN_CANCELLED"]              = "Ban-Phase abgebrochen."
    L["MSG_OPPONENT_NO_ADDON"]      = "Gegner hat kein WG+ installiert."
    L["BANS_PER_PLAYER"]            = "Bans pro Spieler:"
    -- Veto system
    L["VETO_MODE"]                  = "Veto"
    L["VETO_TITLE"]                 = "KARTEN-VETO"
    L["VETO_INVITE_SENT"]           = "Veto-Einladung gesendet an %s (%s)"
    L["VETO_INVITE_RECEIVED"]       = "%s möchte ein %s Karten-Veto starten!"
    L["VETO_ACCEPT"]                = "Annehmen"
    L["VETO_DECLINE"]               = "Ablehnen"
    L["VETO_YOUR_TURN_BAN"]         = "DU BIST DRAN — BANNE eine Karte"
    L["VETO_YOUR_TURN_PICK"]        = "DU BIST DRAN — WÄHLE eine Karte"
    L["VETO_OPPONENT_TURN"]         = "Warte auf %s..."
    L["VETO_BANNED"]                = "%s hat %s gebannt"
    L["VETO_PICKED"]                = "%s hat %s gewählt"
    L["VETO_COMPLETE"]              = "Veto abgeschlossen!"
    L["VETO_FINAL_MAP"]             = "Letzte Karte: %s"
    L["VETO_READY"]                 = "Bereit"
    L["VETO_CANCELLED"]             = "Veto abgebrochen."
    L["VETO_TIMEOUT"]               = "Veto abgelaufen."
    L["VETO_NO_ADDON"]              = "Gegner hat kein WG+ installiert."
    L["VETO_FORMAT_BO1"]            = "Best of 1"
    L["VETO_FORMAT_BO3"]            = "Best of 3"
    L["VETO_FORMAT_BO5"]            = "Best of 5"
    L["VETO_SELECT_FORMAT"]         = "Veto-Format wählen"
    L["VETO_SERIES_MAP"]            = "Karte %d: %s"
    L["VETO_SERIES_LABEL"]          = "SERIENKARTEN"
    L["VETO_HISTORY"]               = "Veto-Verlauf"
    L["VETO_MIN_MAPS"]              = "Mindestens %d Karten für %s Veto benötigt."
    L["VETO_TURN_PROGRESS"]         = "Zug %d / %d"
    L["VETO_START"]                 = "Veto starten"
    -- Map names
    L["Nagrand Arena"]              = "Arena von Nagrand"
    L["Blade's Edge Arena"]         = "Arena des Schergrats"
    L["Ruins of Lordaeron"]         = "Ruinen von Lordaeron"
    L["Dalaran Arena"]              = "Kanalisation von Dalaran"
    L["Tol'viron Arena"]            = "Arena der Tol'vir"
    L["Tiger's Peak"]               = "Tigergipfel"
    L["Ashamane's Fall"]            = "Ashamanes Sturz"
    L["Black Rook Hold Arena"]      = "Arena der Rabenwehr"
    L["Hook Point"]                 = "Hakenkap"
    L["Mugambala"]                  = "Mugambala"
    L["Maldraxxus Coliseum"]        = "Kolosseum von Maldraxxus"
    L["Nokhudon Proving Grounds"]   = "Feuerprobe von Nokhudon"
    L["Warsong Gulch"]              = "Kriegshymnenschlucht"
    L["Twin Peaks"]                 = "Zwillingsgipfel"
    L["Arathi Basin"]               = "Arathibecken"
    L["The Battle for Gilneas"]     = "Schlacht um Gilneas"
    L["Battle for Gilneas"]         = "Schlacht um Gilneas"
    L["Eye of the Storm"]           = "Auge des Sturms"
    L["Temple of Kotmogu"]          = "Tempel von Katmogu"
    L["Silvershard Mines"]          = "Silberbruchmine"
    L["Seething Shore"]             = "Brodelnde Küste"
    L["Deephaul Ravine"]            = "Tiefbeuteschlucht"
    L["Deepwind Gorge"]             = "Tiefenwindschlucht"
    L["The Robodrome"]              = "Das Robodrom"
    L["Empyrean Domain"]            = "Emyriumdomäne"
    L["Enigma Crucible"]            = "Enigmatiegel"
    L["Cage of Carnage"]            = "Käfig des Gemetzels"

elseif LOCALE == "frFR" then
    -- French
    BINDING_NAME_WARGAMESPLUS_TOGGLE = "Afficher/Masquer la fenêtre"
    BINDING_NAME_WARGAMESPLUS_DOCK = "Afficher/Masquer le mode dock"
    L["ADDON_LOADED"]               = "WarGames+ chargé."
    L["FRIENDS"]                    = "AMIS"
    L["THEME_LABEL"]                = "Thème :"
    L["CUSTOM_THEME"]               = "THÈME PERSO"
    L["BASE_LABEL"]                 = "Base :"
    L["TYPE_LABEL"]                 = "Type :"
    L["REFRESH"]                    = "Actualiser"
    L["TARGET"]                     = "Cible"
    L["COLLAPSE"]                   = "Réduire"
    L["EXPAND"]                     = "Agrandir"
    L["STATS"]                      = "Stats"
    L["SPECTATE"]                   = "Observer"
    L["CHALLENGE_MODE"]             = "Défi"
    L["RESET"]                      = "Réinitialiser"
    L["SEND_CHALLENGE"]             = "Envoyer le défi"
    L["SPECTATE_MATCH"]             = "Observer le match"
    L["LEADER_1"]                   = "Chef 1 :"
    L["LEADER_2"]                   = "Chef 2 :"
    L["TOURNAMENT_RULES"]           = "Règles de tournoi"
    L["RECENT_OPPONENTS"]           = "Adversaires récents"
    L["TAB_ARENAS"]                 = "Arènes"
    L["TAB_BATTLEGROUNDS"]          = "Champs de bataille"
    L["MODE_SHUFFLE"]               = "Brassage"
    L["MODE_NORMAL"]                = "Normal"
    L["RANDOM_MAP"]                 = "Carte aléatoire"
    L["WHISPER_CHARACTER"]          = "Chuchoter"
    L["INVITE_CHARACTER"]           = "Inviter"
    L["FAVORITE"]                   = "Favori"
    L["UNFAVORITE"]                 = "Retirer"
    L["VIEW_PROFILE"]               = "Voir le profil"
    L["SEND_CHALLENGE_MENU"]        = "Envoyer le défi"
    L["INCLUDE_IN_RANDOM"]          = "Inclure dans aléatoire"
    L["EXCLUDE_FROM_RANDOM"]        = "Exclure de l'aléatoire"
    L["MSG_CHALLENGE_SENT"]         = "Défi envoyé à %s sur %s"
    L["MSG_RANDOM_SELECTED"]        = "Sélection aléatoire : %s"
    L["MSG_ALL_MAPS_EXCLUDED"]      = "Attention : Toutes les cartes exclues, utilisation du pool complet."
    L["MSG_BOTH_LEADERS_REQUIRED"]  = "Les deux chefs de groupe doivent être spécifiés."
    L["MSG_CANNOT_RESOLVE_BNET"]    = "Impossible de résoudre l'ID BNet pour : %s"
    L["MSG_SPECTATING"]             = "Observation : %s contre %s sur %s"
    L["MSG_HISTORY_CLEARED"]        = "Historique effacé."
    L["MSG_MATCH_RESULT"]           = "Résultat : %s contre %s sur %s"
    L["MATCH_HISTORY"]              = "HISTORIQUE DES MATCHS"
    L["CLEAR_HISTORY"]              = "Effacer l'historique"
    L["CONFIRM_CLEAR"]              = "Confirmer ?"
    L["NO_MATCH_DATA"]              = "Aucune donnée de match"
    L["NO_MATCHES_RECORDED"]        = "Aucun match enregistré"
    L["NO_MATCHES_VS_OPPONENT"]     = "Aucun match contre cet adversaire"
    L["WIN_RATE"]                   = "taux de victoire"
    L["STREAK"]                     = "Série :"
    L["BEST"]                       = "Meilleure :"
    L["CURRENT_STREAK"]             = "Série en cours :"
    L["RECORDS_COUNT"]              = "%d / %d enregistrements"
    L["TAB_OPPONENTS"]              = "Adversaires"
    L["TAB_MAPS"]                   = "Cartes"
    L["TAB_LOG"]                    = "Journal"
    L["YOUR_PERFORMANCE"]           = "VOS PERFORMANCES"
    L["WINNERS"]                    = "VAINQUEURS"
    L["LOSERS"]                     = "PERDANTS"
    L["PLAYERS"]                    = "JOUEURS"
    L["WIN"]                        = "VICTOIRE"
    L["LOSS"]                       = "DÉFAITE"
    L["DRAW"]                       = "NUL"
    L["WIN_SHORT"]                  = "V"
    L["LOSS_SHORT"]                 = "D"
    L["DRAW_SHORT"]                 = "N"
    L["STAT_DMG"]                   = "dégâts"
    L["STAT_HEAL"]                  = "soins"
    L["TIME_SECONDS_AGO"]           = "il y a %ds"
    L["TIME_MINUTES_AGO"]           = "il y a %dm"
    L["TIME_HOURS_AGO"]             = "il y a %dh"
    L["TIME_DAYS_AGO"]              = "il y a %dj"
    L["MAP_EXCLUDED_SUFFIX"]        = "(exclu)"
    L["THEME_ACCENT"]               = "Accent"
    L["THEME_BACKGROUND"]           = "Arrière-plan"
    L["THEME_BORDER"]               = "Bordure"
    L["THEME_BUTTON"]               = "Bouton"
    L["THEME_TEXT"]                  = "Texte"
    L["THEME_CLOSE_HOVER"]          = "Fermer/Survol"
    L["THEME_WIN_COLOR"]            = "Couleur victoire"
    L["THEME_LOSS_COLOR"]           = "Couleur défaite"
    L["MODE_LABEL_SOLO_SHUFFLE"]    = "Brassage solo"
    L["COMPACT"]                    = "Compact"
    L["MAP_STATS_PLAYED"]           = "(%d joués)"
    L["BAN_MODE"]                   = "Bannir cartes"
    L["BAN_SUBMIT"]                 = "Soumettre bans"
    L["BAN_WAITING"]                = "En attente de l'adversaire..."
    L["BAN_COUNT"]                  = "Bans : %d / %d"
    L["BAN_RESULT"]                 = "Carte sélectionnée : %s"
    L["BAN_CANCELLED"]              = "Phase de ban annulée."
    L["MSG_OPPONENT_NO_ADDON"]      = "L'adversaire n'a pas WG+ installé."
    L["BANS_PER_PLAYER"]            = "Bans par joueur :"
    -- Veto system
    L["VETO_MODE"]                  = "Veto"
    L["VETO_TITLE"]                 = "VETO DE CARTE"
    L["VETO_INVITE_SENT"]           = "Invitation veto envoyée à %s (%s)"
    L["VETO_INVITE_RECEIVED"]       = "%s veut démarrer un veto de carte %s !"
    L["VETO_ACCEPT"]                = "Accepter"
    L["VETO_DECLINE"]               = "Refuser"
    L["VETO_YOUR_TURN_BAN"]         = "VOTRE TOUR — BANNIR une carte"
    L["VETO_YOUR_TURN_PICK"]        = "VOTRE TOUR — CHOISIR une carte"
    L["VETO_OPPONENT_TURN"]         = "En attente de %s..."
    L["VETO_BANNED"]                = "%s a banni %s"
    L["VETO_PICKED"]                = "%s a choisi %s"
    L["VETO_COMPLETE"]              = "Veto terminé !"
    L["VETO_FINAL_MAP"]             = "Carte finale : %s"
    L["VETO_READY"]                 = "Prêt"
    L["VETO_CANCELLED"]             = "Veto annulé."
    L["VETO_TIMEOUT"]               = "Veto expiré."
    L["VETO_NO_ADDON"]              = "L'adversaire n'a pas WG+ installé."
    L["VETO_FORMAT_BO1"]            = "Best of 1"
    L["VETO_FORMAT_BO3"]            = "Best of 3"
    L["VETO_FORMAT_BO5"]            = "Best of 5"
    L["VETO_SELECT_FORMAT"]         = "Choisir le format du veto"
    L["VETO_SERIES_MAP"]            = "Carte %d : %s"
    L["VETO_SERIES_LABEL"]          = "CARTES DE LA SÉRIE"
    L["VETO_HISTORY"]               = "Historique des vetos"
    L["VETO_MIN_MAPS"]              = "Il faut au moins %d cartes pour un veto %s."
    L["VETO_TURN_PROGRESS"]         = "Tour %d / %d"
    L["VETO_START"]                 = "Lancer un veto"
    -- Map names
    L["Nagrand Arena"]              = "Arène de Nagrand"
    L["Blade's Edge Arena"]         = "Arène des Tranchantes"
    L["Ruins of Lordaeron"]         = "Ruines de Lordaeron"
    L["Dalaran Arena"]              = "Égouts de Dalaran"
    L["Tol'viron Arena"]            = "Arène Tol'viron"
    L["Tiger's Peak"]               = "Le croc du Tigre"
    L["Ashamane's Fall"]            = "Chute d'Ashamane"
    L["Black Rook Hold Arena"]      = "Arène du bastion du Freux"
    L["Hook Point"]                 = "Pointe du Crochet"
    L["Mugambala"]                  = "Mugambala"
    L["Maldraxxus Coliseum"]        = "Maldraxxus Coliseum"
    L["Nokhudon Proving Grounds"]   = "Ordalie des Nokhuds"
    L["Warsong Gulch"]              = "Goulet des Chanteguerres"
    L["Twin Peaks"]                 = "Pics-Jumeaux"
    L["Arathi Basin"]               = "Bassin Arathi"
    L["The Battle for Gilneas"]     = "La bataille de Gilnéas"
    L["Battle for Gilneas"]         = "La bataille de Gilnéas"
    L["Eye of the Storm"]           = "L'Œil du cyclone"
    L["Temple of Kotmogu"]          = "Temple de Kotmogu"
    L["Silvershard Mines"]          = "Mines d'Éclargent"
    L["Seething Shore"]             = "Rivage Bouillonnant"
    L["Deephaul Ravine"]            = "Ravin d'Abondabîme"
    L["Deepwind Gorge"]             = "Gorge de Vent-Caverneux"
    L["The Robodrome"]              = "Le Robodrome"
    L["Empyrean Domain"]            = "Domaine Empyréen"
    L["Enigma Crucible"]            = "Creuset des Énigmes"
    L["Cage of Carnage"]            = "Cage du Carnage"

elseif LOCALE == "esES" or LOCALE == "esMX" then
    -- Spanish (shared base; esMX-specific overrides below)
    BINDING_NAME_WARGAMESPLUS_TOGGLE = "Mostrar/Ocultar ventana"
    BINDING_NAME_WARGAMESPLUS_DOCK = "Mostrar/Ocultar modo dock"
    L["ADDON_LOADED"]               = "WarGames+ cargado."
    L["FRIENDS"]                    = "AMIGOS"
    L["THEME_LABEL"]                = "Tema:"
    L["CUSTOM_THEME"]               = "TEMA PERSONALIZADO"
    L["BASE_LABEL"]                 = "Base:"
    L["TYPE_LABEL"]                 = "Tipo:"
    L["REFRESH"]                    = "Actualizar"
    L["TARGET"]                     = "Objetivo"
    L["COLLAPSE"]                   = "Colapsar"
    L["EXPAND"]                     = "Expandir"
    L["STATS"]                      = "Estadísticas"
    L["SPECTATE"]                   = "Observar"
    L["CHALLENGE_MODE"]             = "Desafío"
    L["RESET"]                      = "Restablecer"
    L["SEND_CHALLENGE"]             = "Enviar desafío"
    L["SPECTATE_MATCH"]             = "Observar partida"
    L["LEADER_1"]                   = "Líder 1:"
    L["LEADER_2"]                   = "Líder 2:"
    L["TOURNAMENT_RULES"]           = "Reglas de torneo"
    L["RECENT_OPPONENTS"]           = "Oponentes recientes"
    L["TAB_ARENAS"]                 = "Arenas"
    L["TAB_BATTLEGROUNDS"]          = "Campos de batalla"
    L["MODE_SHUFFLE"]               = "Aleatorio"
    L["MODE_NORMAL"]                = "Normal"
    L["RANDOM_MAP"]                 = "Mapa aleatorio"
    L["WHISPER_CHARACTER"]          = "Susurrar"
    L["INVITE_CHARACTER"]           = "Invitar"
    L["FAVORITE"]                   = "Favorito"
    L["UNFAVORITE"]                 = "Quitar favorito"
    L["VIEW_PROFILE"]               = "Ver perfil"
    L["SEND_CHALLENGE_MENU"]        = "Enviar desafío"
    L["INCLUDE_IN_RANDOM"]          = "Incluir en aleatorio"
    L["EXCLUDE_FROM_RANDOM"]        = "Excluir de aleatorio"
    L["MSG_CHALLENGE_SENT"]         = "Desafío enviado a %s en %s"
    L["MSG_RANDOM_SELECTED"]        = "Selección aleatoria: %s"
    L["MSG_ALL_MAPS_EXCLUDED"]      = "Advertencia: Todos los mapas excluidos, usando grupo completo."
    L["MSG_BOTH_LEADERS_REQUIRED"]  = "Ambos líderes de grupo deben ser especificados."
    L["MSG_CANNOT_RESOLVE_BNET"]    = "No se pudo resolver el ID de BNet para: %s"
    L["MSG_SPECTATING"]             = "Observando: %s vs %s en %s"
    L["MSG_HISTORY_CLEARED"]        = "Historial borrado."
    L["MSG_MATCH_RESULT"]           = "Resultado: %s vs %s en %s"
    L["MATCH_HISTORY"]              = "HISTORIAL DE PARTIDAS"
    L["CLEAR_HISTORY"]              = "Borrar historial"
    L["CONFIRM_CLEAR"]              = "¿Confirmar?"
    L["NO_MATCH_DATA"]              = "Sin datos de partida"
    L["NO_MATCHES_RECORDED"]        = "No hay partidas registradas"
    L["NO_MATCHES_VS_OPPONENT"]     = "Sin partidas contra este oponente"
    L["WIN_RATE"]                   = "tasa de victoria"
    L["STREAK"]                     = "Racha:"
    L["BEST"]                       = "Mejor:"
    L["CURRENT_STREAK"]             = "Racha actual:"
    L["RECORDS_COUNT"]              = "%d / %d registros"
    L["TAB_OPPONENTS"]              = "Oponentes"
    L["TAB_MAPS"]                   = "Mapas"
    L["TAB_LOG"]                    = "Registro"
    L["YOUR_PERFORMANCE"]           = "TU RENDIMIENTO"
    L["WINNERS"]                    = "GANADORES"
    L["LOSERS"]                     = "PERDEDORES"
    L["PLAYERS"]                    = "JUGADORES"
    L["WIN"]                        = "VICTORIA"
    L["LOSS"]                       = "DERROTA"
    L["DRAW"]                       = "EMPATE"
    L["WIN_SHORT"]                  = "V"
    L["LOSS_SHORT"]                 = "D"
    L["DRAW_SHORT"]                 = "E"
    L["STAT_DMG"]                   = "daño"
    L["STAT_HEAL"]                  = "sanación"
    L["TIME_SECONDS_AGO"]           = "hace %ds"
    L["TIME_MINUTES_AGO"]           = "hace %dm"
    L["TIME_HOURS_AGO"]             = "hace %dh"
    L["TIME_DAYS_AGO"]              = "hace %dd"
    L["MAP_EXCLUDED_SUFFIX"]        = "(excluido)"
    L["MODE_LABEL_SOLO_SHUFFLE"]    = "Batiburrillo de solitarios"
    L["COMPACT"]                    = "Compacto"
    L["MAP_STATS_PLAYED"]           = "(%d jugados)"
    L["BAN_MODE"]                   = "Banear mapas"
    L["BAN_SUBMIT"]                 = "Enviar bans"
    L["BAN_WAITING"]                = "Esperando al oponente..."
    L["BAN_COUNT"]                  = "Bans: %d / %d"
    L["BAN_RESULT"]                 = "Mapa seleccionado: %s"
    L["BAN_CANCELLED"]              = "Fase de ban cancelada."
    L["MSG_OPPONENT_NO_ADDON"]      = "El oponente no tiene WG+ instalado."
    L["BANS_PER_PLAYER"]            = "Bans por jugador:"
    -- Veto system
    L["VETO_MODE"]                  = "Veto"
    L["VETO_TITLE"]                 = "VETO DE MAPA"
    L["VETO_INVITE_SENT"]           = "Invitación de veto enviada a %s (%s)"
    L["VETO_INVITE_RECEIVED"]       = "¡%s quiere iniciar un veto de mapa %s!"
    L["VETO_ACCEPT"]                = "Aceptar"
    L["VETO_DECLINE"]               = "Rechazar"
    L["VETO_YOUR_TURN_BAN"]         = "TU TURNO — BANEA un mapa"
    L["VETO_YOUR_TURN_PICK"]        = "TU TURNO — ELIGE un mapa"
    L["VETO_OPPONENT_TURN"]         = "Esperando a %s..."
    L["VETO_BANNED"]                = "%s baneó %s"
    L["VETO_PICKED"]                = "%s eligió %s"
    L["VETO_COMPLETE"]              = "¡Veto completado!"
    L["VETO_FINAL_MAP"]             = "Mapa final: %s"
    L["VETO_READY"]                 = "Listo"
    L["VETO_CANCELLED"]             = "Veto cancelado."
    L["VETO_TIMEOUT"]               = "Veto expirado."
    L["VETO_NO_ADDON"]              = "El oponente no tiene WG+ instalado."
    L["VETO_FORMAT_BO1"]            = "Mejor de 1"
    L["VETO_FORMAT_BO3"]            = "Mejor de 3"
    L["VETO_FORMAT_BO5"]            = "Mejor de 5"
    L["VETO_SELECT_FORMAT"]         = "Seleccionar formato de veto"
    L["VETO_SERIES_MAP"]            = "Mapa %d: %s"
    L["VETO_SERIES_LABEL"]          = "MAPAS DE LA SERIE"
    L["VETO_HISTORY"]               = "Historial de vetos"
    L["VETO_MIN_MAPS"]              = "Se necesitan al menos %d mapas para veto %s."
    L["VETO_TURN_PROGRESS"]         = "Turno %d / %d"
    L["VETO_START"]                 = "Iniciar veto"
    -- Map names
    L["Nagrand Arena"]              = "Arena de Nagrand"
    L["Blade's Edge Arena"]         = "Arena Filospada"
    L["Ruins of Lordaeron"]         = "Ruinas de Lordaeron"
    L["Dalaran Arena"]              = "Cloacas de Dalaran"
    L["Tol'viron Arena"]            = "Arena Tol'viron"
    L["Tiger's Peak"]               = "La Cima del Tigre"
    L["Ashamane's Fall"]            = "Caída de Crinceniza"
    L["Black Rook Hold Arena"]      = "Arena del Torreón Grajo Negro"
    L["Hook Point"]                 = "Puntagarfio"
    L["Mugambala"]                  = "Mugambala"
    L["Maldraxxus Coliseum"]        = "Coliseo de Maldraxxus"
    L["Nokhudon Proving Grounds"]   = "Terreno de pruebas Nokhudon"
    L["Warsong Gulch"]              = "Garganta Grito de Guerra"
    L["Twin Peaks"]                 = "Cumbres Gemelas"
    L["Arathi Basin"]               = "Cuenca de Arathi"
    L["The Battle for Gilneas"]     = "La Batalla por Gilneas"
    L["Battle for Gilneas"]         = "La Batalla por Gilneas"
    L["Eye of the Storm"]           = "Ojo de la Tormenta"
    L["Temple of Kotmogu"]          = "Templo de Kotmogu"
    L["Silvershard Mines"]          = "Minas Lonjaplata"
    L["Seething Shore"]             = "Costa Hirviente"
    L["Deephaul Ravine"]            = "Barranco de Cargahonda"
    L["Deepwind Gorge"]             = "Cañón del Céfiro"
    L["The Robodrome"]              = "Robotódromo"
    L["Empyrean Domain"]            = "Dominio Empíreo"
    L["Enigma Crucible"]            = "Crisol Enigma"
    L["Cage of Carnage"]            = "Jaula de la Matanza"

    -- esMX-specific overrides
    if LOCALE == "esMX" then
        L["Seething Shore"]         = "Costa Bullente"
        L["Deephaul Ravine"]        = "Barranco de Infrabundancia"
        L["Ashamane's Fall"]        = "Caída de Ashamane"
        L["Hook Point"]             = "Punta Garfio"
        L["MODE_LABEL_SOLO_SHUFFLE"]= "Aleatorio en solitario"
        L["Enigma Crucible"]        = "Crisol Enigmático"
        L["Cage of Carnage"]        = "Jaula de Carnicería"
    end

elseif LOCALE == "ptBR" then
    -- Brazilian Portuguese
    BINDING_NAME_WARGAMESPLUS_TOGGLE = "Mostrar/Ocultar janela"
    BINDING_NAME_WARGAMESPLUS_DOCK = "Mostrar/Ocultar modo dock"
    L["ADDON_LOADED"]               = "WarGames+ carregado."
    L["FRIENDS"]                    = "AMIGOS"
    L["REFRESH"]                    = "Atualizar"
    L["TARGET"]                     = "Alvo"
    L["COLLAPSE"]                   = "Recolher"
    L["EXPAND"]                     = "Expandir"
    L["STATS"]                      = "Estatísticas"
    L["SPECTATE"]                   = "Assistir"
    L["SEND_CHALLENGE"]             = "Enviar desafio"
    L["SPECTATE_MATCH"]             = "Assistir partida"
    L["LEADER_1"]                   = "Líder 1:"
    L["LEADER_2"]                   = "Líder 2:"
    L["TOURNAMENT_RULES"]           = "Regras de torneio"
    L["RECENT_OPPONENTS"]           = "Oponentes recentes"
    L["TAB_ARENAS"]                 = "Arenas"
    L["TAB_BATTLEGROUNDS"]          = "Campos de batalha"
    L["RANDOM_MAP"]                 = "Mapa aleatório"
    L["MATCH_HISTORY"]              = "HISTÓRICO DE PARTIDAS"
    L["CLEAR_HISTORY"]              = "Limpar histórico"
    L["CONFIRM_CLEAR"]              = "Confirmar?"
    L["NO_MATCH_DATA"]              = "Sem dados de partida"
    L["NO_MATCHES_RECORDED"]        = "Nenhuma partida registrada"
    L["NO_MATCHES_VS_OPPONENT"]     = "Nenhuma partida contra este oponente"
    L["WIN_RATE"]                   = "taxa de vitória"
    L["TAB_OPPONENTS"]              = "Oponentes"
    L["TAB_MAPS"]                   = "Mapas"
    L["TAB_LOG"]                    = "Registro"
    L["WIN"]                        = "VITÓRIA"
    L["LOSS"]                       = "DERROTA"
    L["DRAW"]                       = "EMPATE"
    L["WIN_SHORT"]                  = "V"
    L["LOSS_SHORT"]                 = "D"
    L["DRAW_SHORT"]                 = "E"
    L["MODE_LABEL_SOLO_SHUFFLE"]    = "Solo Mix"
    -- Map names
    L["Nagrand Arena"]              = "Arena de Nagrand"
    L["Blade's Edge Arena"]         = "Arena da Lâmina Afiada"
    L["Ruins of Lordaeron"]         = "Ruínas de Lordaeron"
    L["Dalaran Arena"]              = "Esgotos de Dalaran"
    L["Tol'viron Arena"]            = "Arena Tol'viron"
    L["Tiger's Peak"]               = "O Pico do Tigre"
    L["Ashamane's Fall"]            = "Queda de Ashamane"
    L["Black Rook Hold Arena"]      = "Arena do Castelo Corvo Negro"
    L["Hook Point"]                 = "Ponta do Gancho"
    L["Maldraxxus Coliseum"]        = "Coliseu de Maldraxxus"
    L["Nokhudon Proving Grounds"]   = "Campo de Testes Nokhidon"
    L["Warsong Gulch"]              = "Ravina Brado Guerreiro"
    L["Twin Peaks"]                 = "Montes Gêmeos"
    L["Arathi Basin"]               = "Bacia Arathi"
    L["The Battle for Gilneas"]     = "A Batalha por Guilnéas"
    L["Battle for Gilneas"]         = "A Batalha por Guilnéas"
    L["Eye of the Storm"]           = "Olho da Tormenta"
    L["Temple of Kotmogu"]          = "Templo de Kotmogu"
    L["Silvershard Mines"]          = "Minas Estilhaço Prateado"
    L["Seething Shore"]             = "Praia Fervilhante"
    L["Deephaul Ravine"]            = "Ravina Cargafunda"
    L["Deepwind Gorge"]             = "Desfiladeiro do Vendaval"
    L["The Robodrome"]              = "Robódromo"
    L["Empyrean Domain"]            = "Domínio Empíreo"
    L["Enigma Crucible"]            = "Crisol do Enigma"
    L["Cage of Carnage"]            = "Jaula da Carnificina"

elseif LOCALE == "ruRU" then
    -- Russian
    BINDING_NAME_WARGAMESPLUS_TOGGLE = "Показать/Скрыть окно"
    BINDING_NAME_WARGAMESPLUS_DOCK = "Показать/Скрыть док-панель"
    L["ADDON_LOADED"]               = "WarGames+ загружен."
    L["FRIENDS"]                    = "ДРУЗЬЯ"
    L["REFRESH"]                    = "Обновить"
    L["TARGET"]                     = "Цель"
    L["COLLAPSE"]                   = "Свернуть"
    L["EXPAND"]                     = "Развернуть"
    L["STATS"]                      = "Статистика"
    L["SPECTATE"]                   = "Наблюдать"
    L["SEND_CHALLENGE"]             = "Отправить вызов"
    L["SPECTATE_MATCH"]             = "Наблюдать за матчем"
    L["LEADER_1"]                   = "Лидер 1:"
    L["LEADER_2"]                   = "Лидер 2:"
    L["TOURNAMENT_RULES"]           = "Турнирные правила"
    L["RECENT_OPPONENTS"]           = "Недавние противники"
    L["TAB_ARENAS"]                 = "Арены"
    L["TAB_BATTLEGROUNDS"]          = "Поля боя"
    L["RANDOM_MAP"]                 = "Случайная карта"
    L["MATCH_HISTORY"]              = "ИСТОРИЯ МАТЧЕЙ"
    L["CLEAR_HISTORY"]              = "Очистить историю"
    L["CONFIRM_CLEAR"]              = "Подтвердить?"
    L["NO_MATCH_DATA"]              = "Нет данных о матчах"
    L["NO_MATCHES_RECORDED"]        = "Матчи не записаны"
    L["NO_MATCHES_VS_OPPONENT"]     = "Нет матчей против этого противника"
    L["WIN_RATE"]                   = "процент побед"
    L["TAB_OPPONENTS"]              = "Противники"
    L["TAB_MAPS"]                   = "Карты"
    L["TAB_LOG"]                    = "Журнал"
    L["WIN"]                        = "ПОБЕДА"
    L["LOSS"]                       = "ПОРАЖЕНИЕ"
    L["DRAW"]                       = "НИЧЬЯ"
    L["WIN_SHORT"]                  = "П"
    L["LOSS_SHORT"]                 = "Пор"
    L["DRAW_SHORT"]                 = "Н"
    L["MODE_LABEL_SOLO_SHUFFLE"]    = "Соло-суматоха"
    -- Map names
    L["Nagrand Arena"]              = "Арена Награнда"
    L["Blade's Edge Arena"]         = "Арена Острогорья"
    L["Ruins of Lordaeron"]         = "Руины Лордерона"
    L["Dalaran Arena"]              = "Стоки Даларана"
    L["Tol'viron Arena"]            = "Арена Тол'вир"
    L["Tiger's Peak"]               = "Пик Тигра"
    L["Ashamane's Fall"]            = "Последнее пристанище Пеплошкурой"
    L["Black Rook Hold Arena"]      = "Арена крепости Черной Ладьи"
    L["Hook Point"]                 = "Большой Крюк"
    L["Mugambala"]                  = "Мугамбала"
    L["Maldraxxus Coliseum"]        = "Колизей Малдраксуса"
    L["Nokhudon Proving Grounds"]   = "Арена испытаний Нокхудона"
    L["Warsong Gulch"]              = "Ущелье Песни Войны"
    L["Twin Peaks"]                 = "Два Пика"
    L["Arathi Basin"]               = "Низина Арати"
    L["The Battle for Gilneas"]     = "Битва за Гилнеас"
    L["Battle for Gilneas"]         = "Битва за Гилнеас"
    L["Eye of the Storm"]           = "Око Бури"
    L["Temple of Kotmogu"]          = "Храм Котмогу"
    L["Silvershard Mines"]          = "Сверкающие копи"
    L["Seething Shore"]             = "Бурлящий берег"
    L["Deephaul Ravine"]            = "Золотоносная падь"
    L["Deepwind Gorge"]             = "Каньон Суровых Ветров"
    L["The Robodrome"]              = "Рободром"
    L["Empyrean Domain"]            = "Небесный домен"
    L["Enigma Crucible"]            = "Горнило Тайн"
    L["Cage of Carnage"]            = "Клетка Крови"

elseif LOCALE == "koKR" then
    -- Korean
    BINDING_NAME_WARGAMESPLUS_TOGGLE = "창 표시/숨기기"
    BINDING_NAME_WARGAMESPLUS_DOCK = "독 모드 표시/숨기기"
    L["ADDON_LOADED"]               = "WarGames+ 로드됨."
    L["FRIENDS"]                    = "친구"
    L["REFRESH"]                    = "새로고침"
    L["TARGET"]                     = "대상"
    L["COLLAPSE"]                   = "축소"
    L["EXPAND"]                     = "확장"
    L["STATS"]                      = "통계"
    L["SPECTATE"]                   = "관전"
    L["SEND_CHALLENGE"]             = "도전 보내기"
    L["SPECTATE_MATCH"]             = "경기 관전"
    L["TOURNAMENT_RULES"]           = "토너먼트 규칙"
    L["RECENT_OPPONENTS"]           = "최근 상대"
    L["TAB_ARENAS"]                 = "투기장"
    L["TAB_BATTLEGROUNDS"]          = "전장"
    L["RANDOM_MAP"]                 = "무작위 맵"
    L["MATCH_HISTORY"]              = "경기 기록"
    L["CLEAR_HISTORY"]              = "기록 삭제"
    L["NO_MATCH_DATA"]              = "경기 데이터 없음"
    L["WIN"]                        = "승리"
    L["LOSS"]                       = "패배"
    L["DRAW"]                       = "무승부"
    L["MODE_LABEL_SOLO_SHUFFLE"]    = "1인 조합전"
    -- Map names
    L["Nagrand Arena"]              = "나그란드 투기장"
    L["Blade's Edge Arena"]         = "칼날 산맥 투기장"
    L["Ruins of Lordaeron"]         = "로데론의 폐허"
    L["Dalaran Arena"]              = "달라란 하수도"
    L["Tol'viron Arena"]            = "톨비론 투기장"
    L["Tiger's Peak"]               = "범의 봉우리"
    L["Ashamane's Fall"]            = "아샤메인의 몰락지"
    L["Black Rook Hold Arena"]      = "검은 떼까마귀 요새 투기장"
    L["Hook Point"]                 = "갈고리 시장"
    L["Mugambala"]                  = "무감발라"
    L["Maldraxxus Coliseum"]        = "말드락서스 대경기장"
    L["Nokhudon Proving Grounds"]   = "노쿠드 수련의 장"
    L["Warsong Gulch"]              = "전쟁노래 협곡"
    L["Twin Peaks"]                 = "쌍둥이 봉우리"
    L["Arathi Basin"]               = "아라시 분지"
    L["The Battle for Gilneas"]     = "길니아스 전투지"
    L["Battle for Gilneas"]         = "길니아스 전투지"
    L["Eye of the Storm"]           = "폭풍의 눈"
    L["Temple of Kotmogu"]          = "코트모구의 사원"
    L["Silvershard Mines"]          = "은빛수정 광산"
    L["Seething Shore"]             = "들끓는 해안"
    L["Deephaul Ravine"]            = "깊은광혈 협곡"
    L["Deepwind Gorge"]             = "깊은바람 협곡"
    L["The Robodrome"]              = "로봇 전투장"
    L["Empyrean Domain"]            = "창공의 영지"
    L["Enigma Crucible"]            = "수수께끼 도가니"
    L["Cage of Carnage"]            = "살육의 우리"

elseif LOCALE == "zhCN" then
    -- Simplified Chinese
    BINDING_NAME_WARGAMESPLUS_TOGGLE = "显示/隐藏窗口"
    BINDING_NAME_WARGAMESPLUS_DOCK = "显示/隐藏停靠模式"
    L["ADDON_LOADED"]               = "WarGames+ 已加载。"
    L["FRIENDS"]                    = "好友"
    L["REFRESH"]                    = "刷新"
    L["TARGET"]                     = "目标"
    L["COLLAPSE"]                   = "折叠"
    L["EXPAND"]                     = "展开"
    L["STATS"]                      = "统计"
    L["SPECTATE"]                   = "观战"
    L["SEND_CHALLENGE"]             = "发送挑战"
    L["SPECTATE_MATCH"]             = "观看比赛"
    L["TOURNAMENT_RULES"]           = "锦标赛规则"
    L["RECENT_OPPONENTS"]           = "最近对手"
    L["TAB_ARENAS"]                 = "竞技场"
    L["TAB_BATTLEGROUNDS"]          = "战场"
    L["RANDOM_MAP"]                 = "随机地图"
    L["MATCH_HISTORY"]              = "比赛记录"
    L["CLEAR_HISTORY"]              = "清除记录"
    L["NO_MATCH_DATA"]              = "暂无比赛数据"
    L["WIN"]                        = "胜利"
    L["LOSS"]                       = "失败"
    L["DRAW"]                       = "平局"
    L["MODE_LABEL_SOLO_SHUFFLE"]    = "单排轮斗"
    -- Map names
    L["Nagrand Arena"]              = "纳格兰竞技场"
    L["Blade's Edge Arena"]         = "刀锋山竞技场"
    L["Ruins of Lordaeron"]         = "洛丹伦废墟"
    L["Dalaran Arena"]              = "达拉然下水道"
    L["Tol'viron Arena"]            = "托维尔隆竞技场"
    L["Tiger's Peak"]               = "虎踞峰"
    L["Ashamane's Fall"]            = "阿莎曼之墓"
    L["Black Rook Hold Arena"]      = "黑鸦堡垒竞技场"
    L["Hook Point"]                 = "锚角港"
    L["Mugambala"]                  = "穆贾巴拉"
    L["Maldraxxus Coliseum"]        = "玛卓克萨斯角斗场"
    L["Nokhudon Proving Grounds"]   = "诺库顿试炼场"
    L["Warsong Gulch"]              = "战歌峡谷"
    L["Twin Peaks"]                 = "双子峰"
    L["Arathi Basin"]               = "阿拉希盆地"
    L["The Battle for Gilneas"]     = "吉尔尼斯之战"
    L["Battle for Gilneas"]         = "吉尔尼斯之战"
    L["Eye of the Storm"]           = "风暴之眼"
    L["Temple of Kotmogu"]          = "寇魔古寺"
    L["Silvershard Mines"]          = "碎银矿脉"
    L["Seething Shore"]             = "涌泉海滩"
    L["Deephaul Ravine"]            = "御渊溪谷"
    L["Deepwind Gorge"]             = "深风峡谷"
    L["The Robodrome"]              = "机械天穹"
    L["Empyrean Domain"]            = "苍穹斗域"
    L["Enigma Crucible"]            = "迷阵竞技场"
    L["Cage of Carnage"]            = "赤红围场"

elseif LOCALE == "zhTW" then
    -- Traditional Chinese
    BINDING_NAME_WARGAMESPLUS_TOGGLE = "顯示/隱藏視窗"
    BINDING_NAME_WARGAMESPLUS_DOCK = "顯示/隱藏停靠模式"
    L["ADDON_LOADED"]               = "WarGames+ 已載入。"
    L["FRIENDS"]                    = "好友"
    L["REFRESH"]                    = "重新整理"
    L["TARGET"]                     = "目標"
    L["COLLAPSE"]                   = "摺疊"
    L["EXPAND"]                     = "展開"
    L["STATS"]                      = "統計"
    L["SPECTATE"]                   = "觀戰"
    L["SEND_CHALLENGE"]             = "發送挑戰"
    L["SPECTATE_MATCH"]             = "觀看比賽"
    L["TOURNAMENT_RULES"]           = "錦標賽規則"
    L["RECENT_OPPONENTS"]           = "最近對手"
    L["TAB_ARENAS"]                 = "競技場"
    L["TAB_BATTLEGROUNDS"]          = "戰場"
    L["RANDOM_MAP"]                 = "隨機地圖"
    L["MATCH_HISTORY"]              = "比賽記錄"
    L["CLEAR_HISTORY"]              = "清除記錄"
    L["NO_MATCH_DATA"]              = "暫無比賽數據"
    L["WIN"]                        = "勝利"
    L["LOSS"]                       = "失敗"
    L["DRAW"]                       = "平局"
    L["MODE_LABEL_SOLO_SHUFFLE"]    = "單人隨機"
    -- Map names
    L["Nagrand Arena"]              = "納葛蘭競技場"
    L["Blade's Edge Arena"]         = "劍刃競技場"
    L["Ruins of Lordaeron"]         = "羅德隆廢墟"
    L["Dalaran Arena"]              = "達拉然下水道"
    L["Tol'viron Arena"]            = "托維恩競技場"
    L["Tiger's Peak"]               = "猛虎峰"
    L["Ashamane's Fall"]            = "亞夏曼之殞"
    L["Black Rook Hold Arena"]      = "玄鴉堡競技場"
    L["Hook Point"]                 = "勾角地"
    L["Mugambala"]                  = "穆干巴拉"
    L["Maldraxxus Coliseum"]        = "瑪卓薩斯大競技場"
    L["Nokhudon Proving Grounds"]   = "諾庫敦試煉場"
    L["Warsong Gulch"]              = "戰歌峽谷"
    L["Twin Peaks"]                 = "雙子峰"
    L["Arathi Basin"]               = "阿拉希盆地"
    L["The Battle for Gilneas"]     = "吉爾尼斯之戰"
    L["Battle for Gilneas"]         = "吉爾尼斯之戰"
    L["Eye of the Storm"]           = "暴風之眼"
    L["Temple of Kotmogu"]          = "科特魔古神廟"
    L["Silvershard Mines"]          = "碎銀礦坑"
    L["Seething Shore"]             = "騰湧海岸"
    L["Deephaul Ravine"]            = "礦運深谷"
    L["Deepwind Gorge"]             = "深風峽谷"
    L["The Robodrome"]              = "超爆機械鬥場"
    L["Empyrean Domain"]            = "蒼穹領域"
    L["Enigma Crucible"]            = "神秘之爐"
    L["Cage of Carnage"]            = "兇殘牢籠"

elseif LOCALE == "itIT" then
    -- Italian
    BINDING_NAME_WARGAMESPLUS_TOGGLE = "Mostra/Nascondi finestra"
    BINDING_NAME_WARGAMESPLUS_DOCK = "Mostra/Nascondi modalità dock"
    L["ADDON_LOADED"]               = "WarGames+ caricato."
    L["FRIENDS"]                    = "AMICI"
    L["REFRESH"]                    = "Aggiorna"
    L["TARGET"]                     = "Bersaglio"
    L["COLLAPSE"]                   = "Comprimi"
    L["EXPAND"]                     = "Espandi"
    L["STATS"]                      = "Statistiche"
    L["SPECTATE"]                   = "Osserva"
    L["SEND_CHALLENGE"]             = "Invia sfida"
    L["SPECTATE_MATCH"]             = "Osserva partita"
    L["TOURNAMENT_RULES"]           = "Regole torneo"
    L["RECENT_OPPONENTS"]           = "Avversari recenti"
    L["TAB_ARENAS"]                 = "Arene"
    L["TAB_BATTLEGROUNDS"]          = "Campi di battaglia"
    L["RANDOM_MAP"]                 = "Mappa casuale"
    L["MATCH_HISTORY"]              = "STORICO PARTITE"
    L["CLEAR_HISTORY"]              = "Cancella storico"
    L["NO_MATCH_DATA"]              = "Nessun dato di partita"
    L["WIN"]                        = "VITTORIA"
    L["LOSS"]                       = "SCONFITTA"
    L["DRAW"]                       = "PAREGGIO"
    L["MODE_LABEL_SOLO_SHUFFLE"]    = "Mischia Solitaria"
    -- Map names
    L["Nagrand Arena"]              = "Arena di Nagrand"
    L["Blade's Edge Arena"]         = "Arena di Spinaguzza"
    L["Ruins of Lordaeron"]         = "Rovine di Lordaeron"
    L["Dalaran Arena"]              = "Fogne di Dalaran"
    L["Tol'viron Arena"]            = "Arena Tol'viron"
    L["Tiger's Peak"]               = "Picco della Tigre"
    L["Ashamane's Fall"]            = "Caduta di Grigiomanto"
    L["Black Rook Hold Arena"]      = "Arena del Forte Corvonero"
    L["Hook Point"]                 = "Presidio della Pesca"
    L["Mugambala"]                  = "Mugambala"
    L["Maldraxxus Coliseum"]        = "Maldraxxus Coliseum"
    L["Nokhudon Proving Grounds"]   = "Arena d'Addestramento di Nokhudon"
    L["Warsong Gulch"]              = "Forra dei Cantaguerra"
    L["Twin Peaks"]                 = "Picchi Gemelli"
    L["Arathi Basin"]               = "Bacino d'Arathi"
    L["The Battle for Gilneas"]     = "Battaglia per Gilneas"
    L["Battle for Gilneas"]         = "Battaglia per Gilneas"
    L["Eye of the Storm"]           = "Occhio del Ciclone"
    L["Temple of Kotmogu"]          = "Tempio di Kotmogu"
    L["Silvershard Mines"]          = "Miniere di Cupargento"
    L["Seething Shore"]             = "Spiaggia Ribollente"
    L["Deephaul Ravine"]            = "Gola Cavafonda"
    L["Deepwind Gorge"]             = "Scavi di Ventotetro"
    L["The Robodrome"]              = "Robodromo"
    L["Empyrean Domain"]            = "Dominio Empireo"
    L["Enigma Crucible"]            = "Crogiolo dell'Enigma"
    L["Cage of Carnage"]            = "Gabbia della Carneficina"
end
