-- GENERATED by vpp-tools/export_pet_lua.py at build 12.1.0.69404 -- DO NOT HAND-EDIT.
-- Read ONLY through HDG.StaticData.PetFacts.
HDGR_PetSceneDecorDB = {
  [12245] = { file = 7410980, name = "Paw Pal Bed and Blanket" },
  [12246] = { file = 7413969, name = "Paw Pal Bed" },
  [15290] = { file = 7349991, name = "Cherished Pet's Rug" },
  [25101] = { file = 970227, name = "Westfall Pet Cage" },
  [25102] = { file = 1021562, name = "Crossroads Pet Cage" },
  [25103] = { file = 876116, name = "Crude Pet Cage" },
  [25105] = { file = 6323400, name = "Silvermoon Dragonhawk Incubator" },
  [25106] = { file = 6080227, name = "Cozy Lightbloom Lilypad" },
  [25121] = { file = 5199469, name = "Cozy Bird Nest" },
  [25122] = { file = 6023432, name = "Loyal Companion's Plinth" },
}
