
BugGrabberDB = {
["session"] = 14,
["lastSanitation"] = 3,
["errors"] = {
{
["message"] = "Interface/AddOns/Plumber/Modules/Macros.lua:760: attempt to call a nil value",
["time"] = 1782669728,
["locals"] = "parent=MacroFrame <Blizzard_MacroUI.xml:23>{\n _eqolScaleResetHooked=true\n Inset=MacroFrameInset <SharedUIPanelTemplates.xml:686>\n TitleContainer=Frame <SharedUIPanelTemplates.xml:576>\n MacroSelector=Frame <Blizzard_MacroUI.xml:96>\n _eqolScaleHoverHooked=true\n Bg=MacroFrameBg <SharedUIPanelTemplates.xml:663>\n NineSlice=Frame <SharedUIPanelTemplates.xml:550>\n SelectedMacroButton=MacroFrameSelectedMacroButton <Blizzard_MacroUI.xml:85>\n _eqolMoverDefaults=<table>\n _eqolLayoutEntryId=\"MacroFrame\"\n maxTabWidth=140\n Tabs=<table>\n _eqolMoveDragTargets=<table>\n layoutType=\"PortraitFrameTemplate\"\n _eqolLayoutHooks=true\n PortraitContainer=Frame <SharedUIPanelTemplates.xml:551>\n _eqolDragHooked=true\n _eqolScaleTargetHooked=true\n TopTileStreaks=Texture <SharedUIPanelTemplates.xml:671>\n _eqolMoverEntry=<table>\n CloseButton=MacroFrameCloseButton <SharedUIPanelTemplates.xml:680>\n numTabs=2\n selectedTab=1\n}\nf=Frame <Macros.lua:759>\n(*temporary)=nil\n(*temporary)=Frame <Macros.lua:759>\n(*temporary)=<table>{\n SourceEditBox=MacroFrameText <Blizzard_MacroUI.xml:121>\n macroFrameHooked=true\n}\n(*temporary)=\"attempt to call a nil value\"\nAPI=<table>{\n DreamseedUtil=<table>\n}\nEditorUI=<table>{\n SourceEditBox=MacroFrameText <Blizzard_MacroUI.xml:121>\n macroFrameHooked=true\n}\n",
["stack"] = "[Interface/AddOns/Plumber/Modules/Macros.lua]:760: in function <Interface/AddOns/Plumber/Modules/Macros.lua:756>\n[Interface/AddOns/Plumber/Modules/Macros.lua]:822: in function <Interface/AddOns/Plumber/Modules/Macros.lua:807>\n[Interface/AddOns/Plumber/Modules/Macros.lua]:906: in function <Interface/AddOns/Plumber/Modules/Macros.lua:902>\n[C]: in function 'MacroFrame_LoadUI'\n[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:653: in function 'ShowMacroFrame'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/SlashCommands.lua]:1207: in function '?'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:259: in function 'ParseText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:284: in function 'SendText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:407: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:403>\n",
["session"] = 1,
["counter"] = 1,
},
{
["message"] = "...dOns/Blizzard_MacroUI/Blizzard_MacroIconSelector.lua:130: attempt to perform arithmetic on local 'x' (a nil value)",
["time"] = 1782669735,
["locals"] = "self=MacroPopupFrame <Blizzard_MacroIconSelector.xml:5>{\n BG=Texture <SharedUIPanelTemplates.xml:1635>\n _eqolLayoutEntryId=\"MacroPopupFrame\"\n _eqolScaleResetHooked=true\n _eqolDragHooked=true\n iconFilter=1\n _eqolScaleHoverHooked=true\n _eqolMoveDragTargets=<table>\n editBoxHeaderText=\"Enter Macro Name (Max 16 Characters):\"\n _eqolLayoutHooks=true\n _eqolMoverEntry=<table>\n _eqolDefaultPoints=<table>\n mode=1\n iconDataProvider=<table>\n _eqolScaleTargetHooked=true\n IconSelector=Frame <SharedUIPanelTemplates.xml:1797>\n BorderBox=Frame <SharedUIPanelTemplates.xml:1645>\n _eqolMoverDefaults=<table>\n}\nshown=true\nmacroFrame=MacroFrame <Blizzard_MacroUI.xml:23>{\n _eqolScaleResetHooked=true\n Inset=MacroFrameInset <SharedUIPanelTemplates.xml:686>\n TitleContainer=Frame <SharedUIPanelTemplates.xml:576>\n MacroSelector=Frame <Blizzard_MacroUI.xml:96>\n _eqolScaleHoverHooked=true\n Bg=MacroFrameBg <SharedUIPanelTemplates.xml:663>\n macroMax=120\n NineSlice=Frame <SharedUIPanelTemplates.xml:550>\n SelectedMacroButton=MacroFrameSelectedMacroButton <Blizzard_MacroUI.xml:85>\n _eqolMoverDefaults=<table>\n _eqolLayoutEntryId=\"MacroFrame\"\n maxTabWidth=140\n iconDataProvider=<table>\n Tabs=<table>\n macroBase=0\n _eqolMoveDragTargets=<table>\n layoutType=\"PortraitFrameTemplate\"\n _eqolLayoutHooks=true\n PortraitContainer=Frame <SharedUIPanelTemplates.xml:551>\n _eqolDragHooked=true\n _eqolDefaultPoints=<table>\n _eqolScaleTargetHooked=true\n TopTileStreaks=Texture <SharedUIPanelTemplates.xml:671>\n _eqolMoverEntry=<table>\n CloseButton=MacroFrameCloseButton <SharedUIPanelTemplates.xml:680>\n numTabs=2\n selectedTab=1\n}\nwidth=337.999939\np=nil\nr=nil\nrp=nil\nx=nil\ny=nil\n(*temporary)=nil\n(*temporary)=nil\n(*temporary)=nil\n(*temporary)=\"attempt to perform arithmetic on local 'x' (a nil value)\"\n",
["stack"] = "[Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroIconSelector.lua]:130: in function 'UpdateMacroFramePanelWidth'\n[Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroIconSelector.lua]:36: in function <...dOns/Blizzard_MacroUI/Blizzard_MacroIconSelector.lua:3>\n[C]: ?\n[C]: in function 'Show'\n[Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua]:312: in function <...terface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua:309>\n",
["session"] = 1,
["counter"] = 1,
},
},
}
