
BugGrabberDB = {
["session"] = 1,
["lastSanitation"] = 3,
["errors"] = {
{
["message"] = "Interface/AddOns/Blizzard_SharedXMLBase/MathUtil.lua:81: attempt to compare local 'value' (a secret number value tainted by 'REFlex')",
["time"] = 1773858191,
["locals"] = "value = <no value>\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to compare local 'value' (a secret number value tainted by 'REFlex')\"\n",
["stack"] = "[Interface/AddOns/Blizzard_SharedXMLBase/MathUtil.lua]:81: in function <Interface/AddOns/Blizzard_SharedXMLBase/MathUtil.lua:80>\n[tail call]: ?\n[Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua]:387: in function 'GetDerivedScrollRange'\n[Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua]:392: in function 'GetDerivedScrollOffset'\n[Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua]:158: in function 'FullUpdateInternal'\n[Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua]:754: in function 'FullUpdateInternal'\n[Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua]:124: in function 'FullUpdate'\n[Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua]:721: in function <...ddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua:720>\n[C]: ?\n[Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua]:210: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:209>\n[C]: ?\n[Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua]:213: in function 'TriggerEvent'\n...[Interface/AddOns/Blizzard_Menu/Menu.lua]:1191: in function 'SetMenuDescription'\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:1200: in function <Interface/AddOns/Blizzard_Menu/Menu.lua:1194>\n[C]: in function 'securecallfunction'\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:2344: in function <Interface/AddOns/Blizzard_Menu/Menu.lua:2298>\n[tail call]: ?\n[tail call]: ?\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:2507: in function 'OpenMenu'\n[Interface/AddOns/Blizzard_Menu/DropdownButton.lua]:124: in function 'OpenMenu'\n[Interface/AddOns/Blizzard_Menu/DropdownButton.lua]:145: in function 'SetMenuOpen'\n[Interface/AddOns/Blizzard_Menu/DropdownButton.lua]:105: in function <Interface/AddOns/Blizzard_Menu/DropdownButton.lua:100>\n",
["session"] = 1,
["counter"] = 4,
},
{
["message"] = "Interface/AddOns/Blizzard_SharedXML/LayoutFrame.lua:513: bad argument #1 to 'SetSize' (Usage: self:SetSize(x, y). Secret values are only allowed during untainted execution for this argument.)",
["time"] = 1773858190,
["locals"] = "self = Frame {\n minimumElementWidth = 50\n ignoreAllChildren = true\n ScrollBar = Frame {\n }\n dirty = false\n skipChildLayout = true\n ScrollBox = Frame {\n }\n}\nhadNoAnchors = false\nleft = nil\nright = nil\ntop = nil\nbottom = nil\ndefaulted = nil\nlayoutFrameScale = 0.640000\nfw = <no value>\nfh = 163\n",
["stack"] = "[Interface/AddOns/Blizzard_SharedXML/LayoutFrame.lua]:513: in function 'Layout'\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:1467: in function 'PerformLayout'\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:1191: in function 'SetMenuDescription'\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:1200: in function <Interface/AddOns/Blizzard_Menu/Menu.lua:1194>\n[C]: in function 'securecallfunction'\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:2344: in function <Interface/AddOns/Blizzard_Menu/Menu.lua:2298>\n[tail call]: ?\n[tail call]: ?\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:2507: in function 'OpenMenu'\n[Interface/AddOns/Blizzard_Menu/DropdownButton.lua]:124: in function 'OpenMenu'\n[Interface/AddOns/Blizzard_Menu/DropdownButton.lua]:145: in function 'SetMenuOpen'\n[Interface/AddOns/Blizzard_Menu/DropdownButton.lua]:105: in function <Interface/AddOns/Blizzard_Menu/DropdownButton.lua:100>\n",
["session"] = 1,
["counter"] = 2,
},
{
["message"] = "...ddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBar.lua:213: attempt to perform arithmetic on local 'trackExtent' (a secret number value tainted by 'REFlex')",
["time"] = 1773858189,
["locals"] = "self = Frame {\n Directions = <table> {\n }\n interpolator = <table> {\n }\n scrollPercentage = 0\n panExtentPercentage = 0\n useProportionalThumb = true\n Event = <table> {\n }\n visibleExtentPercentage = 0\n wheelPanScalar = 2\n allowScroll = true\n isScrollController = true\n deferredCallbacks = <table> {\n }\n executingEvents = <table> {\n }\n callbackTables = <table> {\n }\n Back = Button {\n }\n panRepeatTime = 0.100000\n Track = Frame {\n }\n panDelay = 0.500000\n thumbAnchor = \"TOP\"\n hideTrackIfThumbExceedsTrack = false\n hideTrack = false\n minThumbExtent = 23\n snapToInterval = false\n canInterpolateScroll = false\n Forward = Button {\n }\n}\nvisibleExtentPercentage = 0\ntrackExtent = <no value>\nthumb = Button {\n upEndTexture = \"minimal-scrollbar-small-thumb-bottom\"\n desaturateIfDisabled = true\n Middle = Texture {\n }\n deferredCallbacks = <table> {\n }\n callbackTables = <table> {\n }\n executingEvents = <table> {\n }\n overBeginTexture = \"minimal-scrollbar-small-thumb-top-over\"\n downMiddleTexture = \"minimal-scrollbar-small-thumb-middle-down\"\n mouseDownSoundKitID = 1115\n End = Texture {\n }\n Begin = Texture {\n }\n downEndTexture = \"minimal-scrollbar-small-thumb-bottom-down\"\n overEndTexture = \"minimal-scrollbar-small-thumb-bottom-over\"\n overMiddleTexture = \"minimal-scrollbar-small-thumb-middle-over\"\n downBeginTexture = \"minimal-scrollbar-small-thumb-top-down\"\n Event = <table> {\n }\n upMiddleTexture = \"minimal-scrollbar-small-thumb-middle\"\n upBeginTexture = \"minimal-scrollbar-small-thumb-top\"\n}\nthumbExtent = nil\nclampedThumb = false\n(*temporary) = true\n(*temporary) = Frame {\n End = Texture {\n }\n Thumb = Button {\n }\n Middle = Texture {\n }\n Begin = Texture {\n }\n}\n(*temporary) = <no value>\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to perform arithmetic on local 'trackExtent' (a secret number value tainted by 'REFlex')\"\n",
["stack"] = "[Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBar.lua]:213: in function 'Update'\n[Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBar.lua]:47: in function <...ddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBar.lua:46>\n[C]: in function 'Show'\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:2362: in function <Interface/AddOns/Blizzard_Menu/Menu.lua:2298>\n[tail call]: ?\n[tail call]: ?\n[Interface/AddOns/Blizzard_Menu/Menu.lua]:2507: in function 'OpenMenu'\n[Interface/AddOns/Blizzard_Menu/DropdownButton.lua]:124: in function 'OpenMenu'\n[Interface/AddOns/Blizzard_Menu/DropdownButton.lua]:145: in function 'SetMenuOpen'\n[Interface/AddOns/Blizzard_Menu/DropdownButton.lua]:105: in function <Interface/AddOns/Blizzard_Menu/DropdownButton.lua:100>\n",
["session"] = 1,
["counter"] = 1,
},
},
}
